### ISSUE TITLE
Canada.ca theme: Video example page layout & transcript

### ISSUE THREAD

**Issue by MattMoore-GOC** [wet-boew/GCWeb#1005]
Is the video example page (http://wet-boew.github.io/themes-dist/GCWeb/video-en.html) meant to just convey the code for the video player or the layout of a video page?

If the latter:
* What is the purpose of the < h2 >?
* I suggest putting the content *below* the video file so longer descriptions won't push the content too far down the page.
* For the transcript, I have proposed a standard that has been reviewed and received good feedback from the GOC video producers community of practice. It is on GCConnex at: http://gcconnex.gc.ca/file/view/8577467/standard-for-descriptive-transcripts-and-closed-captioning-of-videos

**Comment by pjackson28** [comment]
The h2 is describing the section that contains the video. The section includes the example video, the transcript as well as the code used (in a details/summary). So the heading is associated to the section which contains all three items and is not exclusively associated to the video. So it would confuse things semantically to put the h2 after the video in this case.

I think what you are thinking of is the h3 contained within the figcaption which is after the video, using figure/figcaption to associate it to the video. The description of the video (in the form of the transcript) is also after the video like you suggest.

**Comment by hsrudnicki** [comment]
@MattMoore-GOC : Is this above still an issue?  Please update this issue's status whether this issue can be closed as resolved/fixed based on the last comment from @pjackson28 or otherwise?  Thank you
