### ISSUE TITLE
Need Right Column to Flow Separately on Mobile

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#1017]
@masterbee @dk-tbs @pcwsmith

On Monday, we talked about the potential problem of the Mobile flow of the ‘Supported by’ and ‘Audience’ boxes. As is, they appear BEFORE the topics because the flow had already been adjusted so that Most Req show up before Topics for Mobile, because that's more likely what they need. We worried that on mobile, people might click them before ever seeing the topics, since we already know mobile users are more likely to click links higher on the page. 
![mobile topic flow police](https://cloud.githubusercontent.com/assets/1855584/9549532/86f23c7e-4d74-11e5-81d8-429348a35513.png)

That worry appears to be justified - see the video below. This is exactly the scenario that is most worrying, because the phone user selected the WRONG department from the Supported By box. Ironically, the link is non-functional, so the page just reloaded. I’m not sure she even noticed, because she continued and selected the correct topic link once the page reloaded. 

https://www.youtube.com/watch?v=MVXggjbX2Qs

Today’s phone participant almost went for RCMP in the Supported By too, but stopped herself in time and continued scrolling down to see the topics. 

So it IS important to see if we can get that flow order changed. 

@masterbee can you advise if this is possible? If not, we may need to consider changing the location of those new elements ( the Supported by and Information for boxes) to below the topics so they'll flow properly on mobile.

**Comment by neoinsight** [comment]
@dk-tbs @pcwsmith Update: a second mobile participant had the same issue today, for a different task. She incorrectly selected Public Safety from the Supported by box before scrolling down to see the topics. 

Note also that on a final destination level page, the boxes appear above the topics without even a Most Requested box, as seen below. 

![supported by box above topics](https://cloud.githubusercontent.com/assets/1855584/9587882/055753da-4ff3-11e5-83cc-8a108468c654.png)

**Comment by neoinsight** [comment]
@masterbee @dk-tbs New video summary of this WET issue was presented at ADM WMC https://www.youtube.com/watch?v=A0d0tGKOFUo

**Comment by DK-TBS** [comment]
@shawnthompson and I talked about this a bit, he said he was going to tinker with it to see if there's any way to send only the "most requested" box to the top when rendered on smaller screens.  Shawn, have you had a chance to look into it?  If we can't find a way to get that working, we may need to consider coming up with a different layout/approach for these pages...

**Comment by shawnthompson** [comment]
This should work if we place them right after the topics and we don't let the topics wrap under the right column in desktop view. Which we don't so it should work. I'll look in to it and make the change in GCWeb.

**Comment by neoinsight** [comment]
@shawnthompson Excellent! @DK-TBS When he's got it worked out, can you implement in the prototype and alert me so I can retest this critical issue in the next round of testing?

**Comment by DK-TBS** [comment]
Sure thing, @neoinsight - will do.  Mr @shawnthompson , drop me a line as soon as you've got something to share, I'd love to see it work out.  Hooray!

**Comment by shawnthompson** [comment]
@neoinsight @DK-TBS, just making sure these are only happening on the following pages in the tempates:
- [Theme Landing](http://wet-boew.github.io/themes-dist/GCWeb/theme-en.html)
- [Topic Landing](http://wet-boew.github.io/themes-dist/GCWeb/topic-en.html)

**Comment by DK-TBS** [comment]
@shawnthompson - Yep, we'd want to do this on the Theme and Topic pages, and also on the Large Institutional Profile page, and the Organizational Profile page.  You can see the most up-to-date sidebars for all of these pages in the [latest version of the spec, version 1.2](http://www.gcpedia.gc.ca/gcwiki/images/c/c4/Canada_Site_Content_IA_Specification_HIGH-_V1_2_-EN.pdf).

If we can get that working in principle, then we should talk about going through all the demo templates [up here](http://wet-boew.github.io/themes-dist/GCWeb/index-en.html) to bring them up to spec.  Lots to catch up on, and I want to see if you and Mario are on board with jumping back into the ol' demo template area.  Sounds like config of the MWS is going to take longer than we all thought....

**Comment by shawnthompson** [comment]
@DK-TBS - The [Institutional Profile page](http://wet-boew.github.io/themes-dist/GCWeb/institution-en.html) and [Organizational Profile page] already have the proper flow.

I agree that we need to update these templates. They are following behind from the specs for sure. Right @masterbee?

**Comment by DK-TBS** [comment]
@shawnthompson - Illustration!  Hopefully there's some CSS trickery that can make it work, but I know it's probably a long shot  :)

![sidebar split-up](https://cloud.githubusercontent.com/assets/9662127/11224914/545bec04-8d45-11e5-9fca-b885acc46731.jpg)

Hope life is good brother

**Comment by shawnthompson** [comment]
I really don't think Bootstrap can do this. Maybe if we were using flexbox we might be able to pull this off.
I'd like to bring @cfarquharson in on this. Thoughts from the west?
cc/ @masterbee

**Comment by neoinsight** [comment]
Good idea @shawnthompson because I see other needs for managing the flow this way. For example, RCMP Find Detachment page had to split up the right column flow to have the postal code show above the main table in mobile, and the rest of the right column flow below. Had to do this because of usability testing failures in previous version. Not sure how they did it, just making the point that it's not just this one case. See http://www.rcmp-grc.gc.ca/detach/en

**Comment by DK-TBS** [comment]
@neoinsight - I was all excited to see how they did it, but then discovered that they simply sidestepped the problem by completely hiding the second sidebar element ("locations by province") on smaller screens.  Ack!

**Comment by josephconti31** [comment]
It gets the job done given the constraints we need to work in :+1:

**Comment by neoinsight** [comment]
@josephconti31 Hi there -  Indeed it does!  You can see that we are working to address some of those constraints. If you are facing other issues like this, do let us know.

**Comment by hsrudnicki** [comment]
And since your last comments, have been this issue resolved/fixed or otherwise?  Either way, please again update this issue's status, whether this issue can be closed as fixed or if otherwise?  Thank you

**Comment by pcwsmith** [comment]
I believe @shawnthompson cracked this nut - see http://servicecanada.github.io/GCWeb/topic-en.html

**Comment by shawnthompson** [comment]
You are very right @pcwsmith! Closed!
