### ISSUE TITLE
Canada.ca theme: abbr tag

### ISSUE THREAD

**Issue by muling** [wet-boew/GCWeb#1019]
It seems that in Firefox 40, content with abbr tag have the relative size dotted underline (using text-decoration).  WET4 uses a small dotted underline to style the abbr.  

The result on Firefox is a double-dotted underline.
(Magnified screenshot)
![abbrtag](https://cloud.githubusercontent.com/assets/2365028/9612818/ab571cee-50b5-11e5-97fc-9eaf45cded18.png)

Other browsers do not have this issue.  Could you please correct this?

**Comment by muling** [comment]
Some other examples of the issue:

http://news.gc.ca/web/article-en.do?mthd=advSrch&crtr.mnthndVl=&crtr.mnthStrtVl=&crtr.page=1&nid=1005349&crtr.yrndVl=&crtr.kw=cfia&crtr.yrStrtVl=&crtr.dyStrtVl=&crtr.dyndVl=

http://news.gc.ca/web/article-en.do?nid=891909

**Comment by muling** [comment]
This is related to issue #7043

**Comment by LaurentGoderre** [comment]
Closing since it's a duplicate
