### ISSUE TITLE
Updates to section menu component to facilitate onboarding

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#1022]
Hi everyone!  First, a few shout-outs to draw the attention of some interested parties out there:  @neoinsight, @masterbee, @pjackson28, @pcwsmith, @lucas-hay, @thomasgohard 

As you all know, there’s been a decision to expand the functionality of the section menu component on an interim basis, to help smooth the onboarding process.  We’ve heard a lot of anxiety from various departments about the work involved in changing their IA and content to match the section menus that are currently in the spec doc, and we want to make the move to the MWS as smooth as possible.  Once we’re past the onboarding phase, we can adjust the section menu guidance to be more in line with the ideal end state, to be more like the way we all think it really should be.  During optimization we can push the departments to flatten out their section menus and put the effort/time into cleaning things up.

So here’s the plan.  First, we’ve got to address the small-screen problems caused when the section menus move into the mobile “hamburger” menu.  And we’ll address that by changing the GCweb theme so that the menus drop to the bottom of the page, instead of into the mobile menu.  There’s already an issue in here describing that change.  #995 

The other thing we want to do is allow the section menu to display an additional level of links (the children of the current destination page) to accommodate downward movement deeper into the current task.  So the section menus will display siblings of the current page, and children of the current page.  Later on, we can remove the extra level of links (the children links) and push departments to place those links in the content area, as part of the optimization phase.  At that point they’ll have more time to deal with it properly.

I’ve attached a few mockups of the new design, to show how it should look and to illustrate how it is used as a visitor drills deeper down into a destination area.  

Screen:  **“Bid on opportunities”** is a sub-task page, under the “Selling to Government” task
(Shows the sibling sub-task pages, as well as the children of the current page)

![1 - bid on opportunities](https://cloud.githubusercontent.com/assets/9662127/9880012/e131f554-5b97-11e5-96a8-8d563149fd42.jpg)

Screen:  **“How a bid is selected”** is a sub-sub-task page, under the “Bid on opportunities” page
(Shows the sibling sub-sub-task pages, as well as the children of the current page)

![2 - how a bid is selected](https://cloud.githubusercontent.com/assets/9662127/9880030/e8944392-5b97-11e5-8770-efecec8e962b.jpg)

Screen:  **“By the best technical solution”** is a sub-sub-sub-task page, under the “How a bid is selected” page
(Shows the sibling sub-sub-sub-task pages)

![3 - best technical](https://cloud.githubusercontent.com/assets/9662127/9880041/ef671758-5b97-11e5-9f14-1bbb39c2f069.jpg)

Screen:  **Menu placement on mobile**
(Shows the section menu’s new position underneath page content in small screens)

![new left nav - small screen](https://cloud.githubusercontent.com/assets/9662127/9880049/f83dca2a-5b97-11e5-9246-e0e0c30e214b.jpg)

All questions and comments are welcome.   Mario, once everyone has had a chance to weigh in, we should try to get these changes into the GCweb theme ASAP, so that the updated component has a chance of being available for onboarding.  Do you see anything standing in the way?

Cheers,
Dave

**Comment by neoinsight** [comment]
Will retest with mobile users once this is implemented. Agree with the urgency for on boarding.

**Comment by DK-TBS** [comment]
@masterbee, @lucas-hay, @shawnthompson, @pcwsmith

This thread needs to come back to life!  Guys, can we do this?  

It looks like there's only two little spots of JS that have to be knocked out to make the menu stay at the bottom of the page on mobile.  Sounds like it might be something that could be implemented without an awful amount of work, but correct me if I'm wrong on that.

And the changes to the visual style of the menu aren't too serious, but it might be risky to go ahead and implement it - let me know what you think.  The new menu might have to be held back as an upgrade - something that people can implement when they feel ready.  But regardless:  if we can just build it, then it would be available to the config team, and to any departments who want to get started with it early on their own.  

Here's a [quick and dirty prototype](http://bytowndigital.com/clients/tbs/leftnav_prototype/topic.html) that shows how the menu works.  Follow the topics doormats to find the sub-pages.  It will demo the menu a few levels deep if you follow "Selling to the Government of Canada", "Bid on opportunities", and "How a bid is selected".

@masterbee, have a look and let me know if you can put some time to it.  There's a lot of interest in getting this thing going, we're probably going to need it soon.

**Comment by pcwsmith** [comment]
By way of update - @DK-TBS and @shawnthompson have been hard at work getting this updated. Our next step is to get a prototype together for some usability testing.

**Comment by shawnthompson** [comment]
I believe these are the mock ups and we can close this issue.

http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html

@DK-TBS and @pcwsmith agree?

**Comment by DK-TBS** [comment]
Agree!  Your demo says everything there is to say about it, now.  Nice.
