### ISSUE TITLE
Canada.ca theme: 

### ISSUE THREAD

**Issue by gillianmartin** [wet-boew/GCWeb#1023]
Hi,

On the Theme page template, the carousel buttons do not always scale down when viewed on smaller screens. This means that it is very difficult to read the text/link associated with the image.

See example:
![extra-small browser-template](https://cloud.githubusercontent.com/assets/4185407/9882039/b9ac8b6c-5ba0-11e5-8aa5-5dde2e7e5198.JPG)

This issue is also visible within the Responsive Emulator (http://wet-boew.github.io/wet-boew-legacy/v3.1/test/responsive-emulator.html).
![browser-size-emulater-template](https://cloud.githubusercontent.com/assets/4185407/9881992/7a0b12f8-5ba0-11e5-927b-19066a003d60.JPG)

Thanks,
Gillian Martin

**Comment by LaurentGoderre** [comment]
Duplicate of https://github.com/wet-boew/wet-boew/issues/6039
