### ISSUE TITLE
Template for video centre page

### ISSUE THREAD

**Issue by bsouster** [wet-boew/GCWeb#1043]
Wondering if there's been any work planned or in progress to create a Canada.ca template for a video centre page. It would be a landing page for Government of Canada videos.

I've been asked to get this moving but want to know if there's any interest to collaborate, if there are any other departments with the intention of leveraging such a page to link to their department's videos, I need to know what your requirements would be as well.

**Comment by hsrudnicki** [comment]
Is it still an issue, waiting for an answer?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?   Thank you

**Comment by pcwsmith** [comment]
I see this under a more general pattern for image/video/multimedia galleries, yeah? I believe DND was asking for something like this at one point as well.

Anyhow in terms of getting something into the Canada.ca design specs, we're aware of this, but see it as a lower priority item at present - it's part of our design backlog. A good way forward would be to work on some mockups with an eye to having us integrate them in a future iteration of the spec doc.

**Comment by bsouster** [comment]
Thanks @pcwsmith 
We're still getting a lot of push here to make something happen but have a lot of hesitation without a clear idea of the technical limitations of the WMS. We may go with a rehashed version of the social media table design Canada.ca has and see if we can get that integrated.

@louis-galipeau fyi

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this, thank you

**Comment by pcwsmith** [comment]
This can be closed, since we have it on our workplan for the content and IA spec.

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed.
