### ISSUE TITLE
Canada.ca theme: 

### ISSUE THREAD

**Issue by minjin20** [wet-boew/GCWeb#1045]
I am working on renewing our public-facing applications using WET4 canada.ca theme and have a problem with one of the applications in which the red color text  (I used class 'text-danger' ) over a grey background (a table header) fails to color contrast, I would like to change the text to the dark red, but there seems no ready class in the template. Is that ok if I create a local style file and reference it in the application? Or if there are better solutions?

**Comment by minjin20** [comment]
![image](https://cloud.githubusercontent.com/assets/16004512/11377951/ac3ff354-92b6-11e5-8542-2943621eb967.png)

**Comment by andre-gh** [comment]
I assume the use case is that you want to call attention to a row with an issue in it?

**Comment by andre-gh** [comment]
Regardless, if that is the use case please follow this documentation for coloring a row to be danger: http://getbootstrap.com/css/#tables-contextual-classes

**Comment by minjin20** [comment]
Thanks André! That solved my problem.

**Comment by andre-gh** [comment]
Good to know, just a reminder that it is inaccessible to only report the danger state with color.  Colour should only be used to enhance the information, not be the primary source of it.
