### ISSUE TITLE
WRI - CDN - WET component delivery - Review

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/GCWeb#1046]
Hi everyone!

Weird title but this is related to the CDN solution (min. target solution) for the Web Renewal Initiative.

We're thinking of offering a way for developers to add WET plugins into their pages without actually writing the code. It would abstract the code from the content layer and instead be inserted dynamically on load.

Advantages : Developer doesn't need to know the code, only the parameters required. If WET updates the code the CDN can update the code as well without the developer having to modify all their pages. Reduces chances of WET errors.

Cons : Potentially slow down the page a tad as the CDN loads all the content. Only works for WET plugins that have code and not just CSS classes.

Examples:

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_18/test-samples/gallery-en.shtml
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_18/test-samples/youtube-en.shtml
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_18/test-samples/feeds-en.shtml
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_18/test-samples/calendar-en.shtml

Looking for feedback if we should offer this officially. Feedback from @masterbee @pjackson28 
@shawnthompson @thomasgohard would be greatly appreciated, thanks!

Roch Lambert

**Comment by LaurentGoderre** [comment]
That typically is the purpose of components in a WCMS. @sylus has been doing this for years in the drupal variant and it couldn't be simpler.

**Comment by rlambert27** [comment]
Hi @LaurentGoderre so you're saying this is good? If I don't hear anything back by COB friday i'll go ahead and this to the documentation for the CDN.

**Comment by masterbee** [comment]
@rlambert27 - The idea is interesting but just to be clear this means that the application layer would still need to update JS code snippets correct? In other words if there is a change to the parameters to the component then application would need to open there application and recode there output correct? 

Normally this type of code change is not ideal but WET has component parameters changes more times than not, so just putting on my application implementors hat for a second. 

I can see the advantage of minimizing the code changes for changes in WET but there is still a level of responsibility on the application in this implementation if plugin changes in terms of parameters. 

As an aside question - are these plugins being loaded after the WET is loaded? Like using the .ready function? If I can see your point on the delayed load and was wondering if there was from frugality being done in terms of working with the component authors about FOC ( Flash of Unstyled content ) that appears in some. Not that is horrible but some plugins need a bit to tweaking to make it as elegant as the samples you have here.

**Comment by rlambert27** [comment]
@masterbee - If a WET component did change a parameter name it would not require updating or tweaking. The JS is located in the CDN not on the application side. The variables being provided are the ones we created on the Closure side in the SOY templates, we transform those variables into the correct names when we output the JS file.

So let's say in v4.0.18 the YouTube plugin is wb-mltmd but in 4.0.19 the plugin is wb-utube, the application would have no tweaking to do because the JS file output by Closure would output the correct variable name. Since the CDN has a "versioning" system it would not clash with previous versions.

Now if the YouTube plugin adds new parameters that is required then this might impact the application. The JS file could add "default" variables when a parameter is not provided but this might not be sufficient. Although, to play devil's advocate, at this point whether you were using the CDN or not you would need to go into your application and update your code anyway. 

We made no changes to how WET is being loaded other than loading the Google Closure files first as they contain the location to all the WET files.

**Comment by LaurentGoderre** [comment]
I don't personally think this should be client-side like that no, I think the WCMS should handle the components. It creates multiple level of processing and it is likely to affect performance on mobile.

**Comment by rlambert27** [comment]
@LaurentGoderre  - I agree that an application built inside a WCMS should use the WCMS for the WET components. The CDN though is targeted towards web applications that will not be in the MWS and most likely not using any type of WCMS.

For the mobile performance we did perform some benchmarks and noticed no significant increase in mobile loading times. We're also pretty sure they will be on par once the files are loaded from the canada.ca on the akamai network.

**Comment by LaurentGoderre** [comment]
It's not the load time but the execution time I was referring to. This added with the apps own logic processing could become problematic.

**Comment by hsrudnicki** [comment]
Is this above still an issue?  Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise?  Thank you
