### ISSUE TITLE
Canada.ca theme: 

### ISSUE THREAD

**Issue by aemh** [wet-boew/GCWeb#1047]
Will an Institutional Profile template be created for Arm's length Institutions, as outlined on p. 90 in the latest version of the Content and Information Architecture Specification (Version 1.2)?

**Comment by DK-TBS** [comment]
@aemh - The development team at Service Canada is about to begin working through a list of page templates, creating new ones and updating others to match the latest version of the spec.  I'll make sure this one is added to the list and will work with the guys to get it built up along with the others.

**Comment by aemh** [comment]
Sounds great! Thanks so much for the quick response.
Regards,
Amanda

**Comment by hsrudnicki** [comment]
@aemh and others: Can be this issue closed as resolved/fixed based on the last comment from @DK-TBS or otherwise?  Thank you

**Comment by DK-TBS** [comment]
The arms-length stuff is definitely in the works... it's in the list, there's just a bit of a backlog.  So it's probably safe to close the issue, and @aemh can keep an eye on the [demo templates page](http://wet-boew.github.io/themes-dist/GCWeb/index-en.html) for the templates to appear once the team has had a chance to put them together...

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed as resolved. Thank you
