### ISSUE TITLE
Topic page template usability: move 'All related' links in line on left

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#1060]
As discussed with @dk-tbs, @pcwsmith
In recent usability testing with 21 participants, many did not notice the All related guidance link as shown in the image below. 
![image](https://cloud.githubusercontent.com/assets/1855584/12521183/1c9ad504-c117-11e5-814f-abbcb9f4bd46.png)

However, they did notice this 'Show more' link that was in-line with the list, so that the gaze flow along the list was completed at the action. 
![image](https://cloud.githubusercontent.com/assets/1855584/12521252/87c72576-c117-11e5-95c5-0c2dd40cabed.png)

Based on this, recommend moving the 'All related' links for all of those sections in 'What we are doing' so that they are left justified and inline with their associated lists.

**Comment by pcwsmith** [comment]
Noted - @DK-TBS has already started looking across the design templates for where this pattern shows up - it's in lots of places!

**Comment by hsrudnicki** [comment]
Please update the status/milestone of this, whether this remains an issue or otherwise?

**Comment by DK-TBS** [comment]
I think it's safe to close this issue for now.  I've got this in my list of things to update in future versions of the C&IA spec document, and then some time after that happens those updates can be done all at once...
