### ISSUE TITLE
Data Ajax shouldn't be used as an alternative to flexbox on theme/topic pages

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/GCWeb#1063]
@shawnthompson I've noticed that PR #1058 resolved issue #1017 by using the Data Ajax plugin in a creative way :P. However, that solution doesn't play nicely with screen readers, browsers with JS disabled, nor non-WebKit desktop browsers (i.e. Firefox, IE, Edge, etc...).

Let's use [GCWeb's topic page](http://wet-boew.github.io/themes-dist/GCWeb/topic-en.html) as an example...

**HTML code structure:**

1. Intro content
2. Most requested
3. Services and information (sets an ID for itself, uses ``class="hidden-md hidden-lg"`` and contains a details element)
4. Supported by
5. More information for
6. (Data Ajax reference to the Services and information section's ID and uses ``class="hidden-sm hidden-xs"``)

**Visual layout in desktop browsers:**

1. Intro content
2. Left column (Services and Information - AJAXed-in)
3. Right column (Most requested, Supported by, More information for)

**Visual layout in mobile browsers:**

1. Intro content
2. Most requested
3. Services and information (original location)
4. Supported by
5. More information for

**What's happening:**
Data Ajax is being used to copy the Services and information section to the bottom of the page, along with some CSS classes to hide or show it depending on the current browser's viewport size.

**Problems:**

1. Screen readers don't care about the ``visible-*`` classes. So assuming JS is enabled, the Services and information section will get duplicated to 2 different spots in the page for screen readers. That may lead to confusion/frustration.
2. The Services and information section gets completely hidden on browsers that have JS disabled (and CSS enabled). So those users are deprived of what could be considered to be the topic page's "main" content. This goes against the spirit of progressive enhancement.
3. The Services and information's section contains a ``<details>`` element. When that section gets AJAXed-in, the Data Ajax plugin doesn't attempt to auto-initialize the details/summary polyfill in browsers that need it. That leaves current versions of Firefox, IE and Edge in the dust. No one using those browsers can expand/collapse anything. This is related to wet-boew/wet-boew#7375.

**Proposed solution:**
Avoid using Data Ajax as a means of re-arranging the visual layout of content. Use flexbox CSS instead (and workarounds for IE as needed).

**Comment by LaurentGoderre** [comment]
1. Actually, screen reader should respect visible-* because it;s using `display: none` which hides content from the DOM entirely.

3. We can probably fix that.

I am not sure we can easily use FlexBox in bootstrap3 without lossing the ability to use grids.

**Comment by masterbee** [comment]
@EricDunsworth agree with @LaurentGoderre screen reader implementation with `display:none` is playing a bit of a culprit here if it is not hiding it from the DOM entirely as it should. 

Flexbox is an interesting option and on the radar for Bootstrap 4 as an enabled property so it is an option down the road to consider. http://v4-alpha.getbootstrap.com/getting-started/flexbox/

**Comment by EricDunsworth** [comment]
@LaurentGoderre @masterbee My bad about item 1 :(. Didn't realize it used ``display: none;``. I had mistakenly assumed its CSS properties were similar to ``wb-inv`` (visually hiding things in a screen reader-friendly way). I guess it isn't anything to worry about then.

Items 2 and 3 still stand though :(.

IMO item 2 could be resolved by adding something along the lines of ``hidden-*-js`` classes that work just like regular ``hidden-*`` classes, but supported by a ``.no-js`` override (to become visible when JS support is missing). Could work as flexbox-free quick fix. @masterbee Any idea when Bootstrap 4.0 might come to WET?

As for item 3 (wet-boew/wet-boew#7375), it should probably be resolved before any real pages on Canada.ca start adopting the new topic/theme page templates. Otherwise no one except Chrome/Opera users will be able to view any expand/collapse content in large views.

**Comment by shawnthompson** [comment]
Do we still care about users who disable JS?

**Comment by EricDunsworth** [comment]
@shawnthompson I guess that would depend on if a decision has been made for WET to move away from the concept of Progressive Enhancement.

It should be noted that all of WET 4.0's page templates still contain various elements designed to play nicely with JS being disabled. For instance, all page templates contain hardcoded references to the ``no-js`` class on their ``<html>`` elements. The skip nav links also contain a "Basic HTML version" link  that pretty much disables all JS.

If a decision is made to officially cease supporting browsers with JS disabled, there'd be value in removing the aforementioned features from WET. No point in keeping them if they're only partially functional.

**Comment by MRicher** [comment]
Instead of using the data ajax, the pull-left and pull-right would of done the same thing.  I'll forward you something @shawnthompson.
