### ISSUE TITLE
Canada.ca theme: font-weight:bold missing from theme.min.css?

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/GCWeb#1075]
Is font-weight:bold missing from table>thead>tr>th in theme.min.css for version 4.0.20?

**Comment by juliemercier** [comment]
Should we just go ahead and bold the <th> while you look into this?

**Comment by shawnthompson** [comment]
@juliemercier, the `th` on the [content page](http://wet-boew.github.io/themes-dist/GCWeb/content-en.html) in the GCWeb pages shows the `font-weight: 700` being applied. This is for the latest developemnt code but I don't think we have changed it since 4.0.20.

**Comment by DK-TBS** [comment]
I'm not seeing it either... the code shows font-weight:300 being inherited from the BODY, and no sign of 700 anywhere.  It doesn't look bold onscreen, either.  Something fishy in there  :)

**Comment by shawnthompson** [comment]
This is what I'm seeing both within the GoC network on Firefox and on my external Rogers network on Chrome. I figured it out! It's the default browser styling that's making it **bold**. Chrome does bold and Firefox gives it 700 weight, but IE does nothing. Maybe we should fix this in the WET base as a Bootstrap override.

![image](https://cloud.githubusercontent.com/assets/2575266/13706618/d6a31768-e773-11e5-95a4-569b10b44d2c.png)

**Comment by juliemercier** [comment]
According to the Computed tab on F12, it's actually font-weight:400
![font-weight](https://cloud.githubusercontent.com/assets/7468426/13706699/304ded42-e774-11e5-8422-7e614c10e160.PNG)

**Comment by shawnthompson** [comment]
MS Edge doesn't make it bold either. Grrrrr Microsoft!

**Comment by shawnthompson** [comment]
#1070 fixes this problem, sorry I missed that PR.

**Comment by shawnthompson** [comment]
Fixed in PR above
