### ISSUE TITLE
Canada.ca Theme design guidelines

### ISSUE THREAD

**Issue by johnpalaganas** [wet-boew/GCWeb#1077]
Hello,

I'm seeking some design guidelines for the Canada.ca theme. I want to know the core philosophy, brand guidelines and intended goal for the usage of the theme. Is there such documentation? Like how FIP has documentation.

We're about to start a redesign and I want to make sure we're within the boundaries.

Thank you,
John

**Comment by pcwsmith** [comment]
Hi John - do you have access to GCpedia? There's a lot of documentation there. If not, send me an email and I can help you out. thx

**Comment by johnpalaganas** [comment]
Thanks @pcwsmith I sent you an email.

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise?

**Comment by johnpalaganas** [comment]
Yes, please close.
