### ISSUE TITLE
"Skip to section menu" link is missing from section menu examples page

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/GCWeb#1083]
The title pretty much says it all.

In [GCWeb's section menu examples page](http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html), the skipnav links currently look like this:
```
<ul id="wb-tphp">
	<li class="wb-slc"><a class="wb-sl" href="#wb-cont">Skip to main content</a></li>
	<li class="wb-slc visible-sm visible-md visible-lg"><a class="wb-sl" href="#wb-info">Skip to "About this site"</a></li>
</ul>
```

Now lets compare that to the [WET theme's secondary menu page](http://wet-boew.github.io/v4.0-ci/theme/content-secmenu-en.html):
```
<ul id="wb-tphp">
	<li class="wb-slc"><a class="wb-sl" href="#wb-cont">Skip to main content</a></li>
	<li class="wb-slc visible-sm visible-md visible-lg"><a class="wb-sl" href="#wb-info">Skip to "About this site"</a></li>
	<li class="wb-slc visible-md visible-lg"><a class="wb-sl" href="#wb-sec">Skip to section menu</a></li>
</ul>
```

The last link seems to be missing from GCWeb :(. Its purpose is to allow screen reader users to quickly and easily jump into the left menu. Without it, it's more difficult for that audience to navigate to left navs in GCWeb.

Any chance it could be added?

**Comment by shawnthompson** [comment]
I think the left menu does not have the same meaning in GCWeb as it does it did in the older version.

Thoughts? 
cc/ @DK-TBS, @pcwsmith, @pjackson28

**Comment by pjackson28** [comment]
@shawnthompson The GCWeb one is implemented incorrectly. It is supposed to have three skip links like the WET theme. Looks like someone used the non-left nav template to create a left nav template.

You can tell by looking at a WET theme page without the left nav (http://wet-boew.github.io/wet-boew/index-en.html):
```html
<ul id="wb-tphp">
<li class="wb-slc">
<a class="wb-sl" href="#wb-cont">Skip to main content</a>
</li>
<li class="wb-slc visible-sm visible-md visible-lg">
<a class="wb-sl" href="#wb-info">Skip to "About this site"</a>
</li>
</ul>
```

**Comment by shawnthompson** [comment]
Awesome, I'll fix that. Thanks @pjackson28
