### ISSUE TITLE
Canada.ca theme: Splash page different than the one on canada.ca

### ISSUE THREAD

**Issue by juliemercier** [wet-boew/GCWeb#1089]
Just noticed that the live Canada.ca splash page has an image rotation on refresh that is not on the Canada.ca splash page template offered on the template page. Should we be adding the image rotation code for application splash pages? Also, on this template, the only indication of the application name is in the title tag. There is a h1 tag but it is only visible to assistive technology. Should we be making the application name more visible on the splash page?

**Comment by rlambert27** [comment]
Hi Julie, 

Please note that splash pages should be avoided at all costs! Unless you have an active bilingual domain name currently in production you should not be using any splash pages. As per the URL strategy for Canada.ca you must redirect users to the main English or French pages when language is known. So if the user is using the English domain name of your app they should resolve to the English main page.

Splash pages are only allowed as an interim measure until you have aligned with the Canada.ca URL strategy and it does not contain any allowances for bilingual domains making splash pages unnecessary!

Page to URL strategy : http://www.gcpedia.gc.ca/wiki/Migration_and_Onboarding_-_Web_Renewal_Toolkit#URL_Strategy

I hope this helps, GCWeb team will correct me if i'm wrong!

**Comment by JasonTBS** [comment]
Can you clarify what you mean by an "active bilingual domain name currently in production?" Our applications currently reside on active bilingual .gc.ca domain names but the migration would require a new domain name that is a sub-domain of Canada.CA which is not yet "active" and required to be unilingual. 

That leads me to another question that I will attempt a scenario to help understand better: What is the direction for served page content language if the sub-domain chosen for canada.ca is not a keyword, but a string (as allowed by exception) and that string is not bilingual however is a word with the same spelling in both French and English, such as the word "role"? In this scenario, maybe the path part is a keyword that is also spelled the same, lets say "/entrepreneur/". This may be the root level of the application but at this point the language is not yet known. Are we to default the served page to be English? Consider that links to the page may not come from within the Canada.ca site but have been linked to by various other sites.

**Comment by rlambert27** [comment]
So if you have an active bilingual domain name that you will keep active post-migration then you'll need a splash page until you phase it out. Once your migration is complete you'll have a Canada.ca sub-domain which will be unilingual, hence no splash page will be necessary.

For your second question i'll leave it up to the GCWeb team to answer. My impression would be that they would not be using terminology at the root level that is spelled the same way in both languages. Those sub-domain keywords are supposed to be pretty specific anyway, I don't think their would be very many scenarios where the keyword would be both specific AND spelled the same way in french and english.

**Comment by hsrudnicki** [comment]
Does this remain still an open issue? Please update the status of this, whether this can be closed or otherwise, thank you
