### ISSUE TITLE
Application menu in Canada.ca theme

### ISSUE THREAD

**Issue by ericenns** [wet-boew/GCWeb#1096]
I have been developing an application and I can't find any information on how one should implement an application menu in the Canada.ca theme

**Comment by RobJohnston** [comment]
Would an application menu be like a left-side menu (what they call a section menu)?  See the example here:  http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html

**Comment by ericenns** [comment]
Nope not a left-side menu, you can see my application [https://hydra.canada.ca](here) with the Government of Canada (GC) Web Usability theme

**Comment by ericenns** [comment]
The application is a non-login/login application, so it can be used either by logging in or without logging in.

**Comment by LaurentGoderre** [comment]
The menu is quite simple. Couldn't the navigation be done in the body of the page?

**Comment by ericenns** [comment]
Take the tour available on the main page to see how a user might use the application. Also you can view an example result from the application [here](https://hydra.canada.ca/analyses/tutorial-analysis)

**Comment by ericenns** [comment]
Would [this](http://codepen.io/anon/pen/grXzqN) be acceptable

**Comment by pcwsmith** [comment]
thumbs up for in-page nav.

but is there only one option under the Advanced label?

**Comment by ericenns** [comment]
There can be two options, it will only show up once the user has done a certain thing.

**Comment by RobJohnston** [comment]
Maybe an overlay?  http://wet-boew.github.io/wet-boew/demos/overlay/overlay-en.html.  Just an idea.
