### ISSUE TITLE
Canada.ca theme: Issues with Search in Top Nav

### ISSUE THREAD

**Issue by ciclerou** [wet-boew/GCWeb#1100]
I went on Canada.ca and entered 'acronym' in the search field and clicked the search button.  I am using Windows 7, IE 11 with a Toshiba Portege R830 laptop.  The search results plage display the navigation menu justified vertically.  See attached.
![searchcanada](https://cloud.githubusercontent.com/assets/2150730/14388456/3a376392-fd7c-11e5-832c-f06bb34918e7.PNG)

**Comment by LaurentGoderre** [comment]
I am unable to reproduce on my IE11. Was this on a work network?

**Comment by MaximMartel** [comment]
same here, tested with FF, Opera and IE11 on SC internal network, unable to reproduce.

**Comment by ciclerou** [comment]
This was on a work network yes at Treasury Board.  It does not happen for everyone's computer.  When I inspect element, I do get a warning message (attached) that says "The attached page targets document mode 7.  Some console APIs and features may not be available.
![inspectelement](https://cloud.githubusercontent.com/assets/2150730/14389540/1533e3f4-fd81-11e5-86bb-0aef026f96f8.PNG)

**Comment by LaurentGoderre** [comment]
This type of issues is common on that network. I don't believe this is an issue with WET

**Comment by ciclerou** [comment]
Great thanks for feedback
