### ISSUE TITLE
Canada.ca theme: Advanced service initiation pages

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/GCWeb#1101]
I was looking at the the "Advanced service initiation pages" provided under the "Canada.ca" link in the Working examples (http://wet-boew.github.io/themes-dist/GCWeb/index-en.html) and it has the following breadcrumb trail. Refer to the screenshot.
![service](https://cloud.githubusercontent.com/assets/12256067/14391266/03fdb18e-fd89-11e5-925c-2c0957e7e605.gif)
Shouldn't the "Institution name" be "Theme name" as it includes the "Institution

 byline right below the "h1"? I noticed the Simple service initiation landing page (http://wet-boew.github.io/themes-dist/GCWeb/service-en.html) has the "Theme name" instead of "Institution name".

Please confirm what it should be "Institution name" or "Theme name".
Thanks,
Saratha

**Comment by DK-TBS** [comment]
Both types of service initiation pages should show the institution name in the crumb trail, not the theme name.  

Hey @shawnthompson!  When you get a chance would you make that correction on the simple service page, in the crumb trail?  That should help make it a little clearer  :)

**Comment by sarasuri** [comment]
Hi,
If it should be the institution name in the breadcrumb trail wouldn't it be redundant since the institution name is also included right below the "h1" as part of the institutional byline.

**Comment by shawnthompson** [comment]
@DK-TBS PR in #1102, this fixes the breadcrumb to link to the Institution name instead of the theme as you requested. I believe this change is aligned with what's in the _Spec_, if so let's close this issue and @sarasuri, you can maybe open another issue to make the suggestion to change the _IA spec_.

**Comment by DK-TBS** [comment]
The crumb trail is a navigation mechanism;  it's purpose is not to identify the content owner, but to help people move back up the site's IA.  If a visitor wants to know which institution owns the page content, they won't necessarily think to look for it in the crumb trail.  

The purpose of the institutional byline is to make it crystal clear, right in the content area, which department is responsible for the page.  Departments have been anxious about this;  they want their involvement to be very clear.  The byline satisfies this requirement better than the crumb trail would.

We do have some concerns about the placement and presentation of the institutional byline.  It may very well end up being moved or removed in some future iteration of the Canada.ca design.  But for now, it's got to stay - we know that a good chunk of visitors are going to be looking for institution names as they explore the site, and we want to make it easy for them to do that  :)

**Comment by DK-TBS** [comment]
Thanks @shawnthompson - much appreciated
