### ISSUE TITLE
Duplicate content on GoC activities and initiatives page

### ISSUE THREAD

**Issue by biljanap** [wet-boew/GCWeb#1109]
GoC activities and initiatives are displayed twice in GoC activities and initiatives page [https://www.canada.ca/content/canadasite/en/activities.html](url).
![goc-duplicates](https://cloud.githubusercontent.com/assets/2146304/14752630/6785db8a-089e-11e6-9eea-d88ce0f3973f.jpg)

**Comment by hsrudnicki** [comment]
Is this still an issue?

**Comment by pcwsmith** [comment]
Looks like that page is still there. How does one even get to it? I don't see where it fits in the IA...?

**Comment by RobJohnston** [comment]
The link that the OC gave goes to the wrong place.  It should be this:  [https://www.canada.ca/content/canadasite/en/activities.html] (https://www.canada.ca/content/canadasite/en/activities.html)

**Comment by biljanap** [comment]
@pcwsmith you get the link to this page when you are in Basic HTML mode. The content of "Government of Canada activities and initiatives" section gets replaced by the link to the page that contains this duplicate content. It happens on the pages that use data-ajax-replace to load the "Government of Canada activities and initiatives". Examples: Travel https://travel.gc.ca/?_ga=1.220056026.2128435990.1472649865&wbdisable=true, News (http://news.gc.ca/web/index-en.do?_ga=1.199257197.2128435990.1472649865&wbdisable=true).

**Comment by pcwsmith** [comment]
thanks for the clarification - so all in all, it looks like this is still an issue

**Comment by TouficS** [comment]
Some visitors to our site were confused while navigating the site with wbdisable=true.
 
Basically, users get to the site from google with the Basic mode without knowing and never switch to standard mode. can we use a note explaining what's basic mode (similar to gmail) as proposed in https://github.com/wet-boew/wet-boew/issues/7457
