### ISSUE TITLE
Icons Spoken by VoiceOver Screenreader on iPhones

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#1133]
As discussed in the Accessibility results, we had 3 usability testing participants with visual disabilities test Canada.ca tasks on their iPhones using VoiceOver. While most of the site worked really well, many of the Bootstrap icons are being turned into spoken emojis. For example, the hamburger menu is read out by VoiceOver as **_"Kissmark Raised Hand Search and Menus"_**. 
- @shawnthompson has identified the problem and ARIA-hidden solution for the icons, as outlined here: http://pauljadam.com/blog/wai-aria-rolealert-on-static-warning-messages-stopping-voiceover-for-ios-from-speaking-css-generated-content-icons-with-aria-hidden/

Need to apply this solution to the Canada.ca menus and page templates.

**Comment by shawnthompson** [comment]
@masterbee I suggest we use JS to add this fix so we don't have to add it to the HTML source on every glyphicons.

**Comment by neoinsight** [comment]
Great idea - built-in accessibility like the rest of WET.

**Comment by RobJohnston** [comment]
Relate to this:  https://github.com/wet-boew/wet-boew/issues/7413

**Comment by shawnthompson** [comment]
Thanks @RobJohnston I missed that issue.

**Comment by shawnthompson** [comment]
@RobJohnston , Actually I don't think it's the same problem. #7413 is talking about SVGs and we are talking about icon fonts.

**Comment by RobJohnston** [comment]
It's "Kissmark" that made me recall the issue.  In #7413, he thought it was an SVG, but wasn't sure.  Might be the same, might not... that's why I didn't say it was a duplicate.

**Comment by shawnthompson** [comment]
I found this interesting article about icon-fonts, it talks about this problem and others.

**Comment by shawnthompson** [comment]
forgot to post the article... oops
https://www.filamentgroup.com/lab/bulletproof_icon_fonts.html

**Comment by neoinsight** [comment]
Just a reminder that we not let this go stale - in the recent tests with VoiceOver participants, the icon in the WET warning box is read out as 'Face screaming in fear'. A bit over the top for a warning about a postal strike!  
![image](https://cloud.githubusercontent.com/assets/1855584/17113550/3d2db7fc-5279-11e6-95ca-e87424c2ca3e.png)
Copying @TouficS as that's a CIC page. 
http://www.cic.gc.ca/english/passport/apply/renew/apply-how.asp

**Comment by nschonni** [comment]
The alert icon uses the unicode character e107. This is part of the private unicode space, but it looks like Softbank Emoji used in <iOS5 didn't respect the unicode spec http://www.iemoji.com/view/emoji/28/people/face-screaming-in-fear

**Comment by hsrudnicki** [comment]
Can be this closed as resolved or otherwise?

**Comment by neoinsight** [comment]
This appears to have been resolved by Bootstrap - terrific.  Just tested on Voice Over and no more 'Kissmarks'!!
