### ISSUE TITLE
Removing horizontal lines on definition lists

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#1158]
@shawnthompson – Hey Shawn!  I’m not sure if you were dialed into the meeting or not, but we met with the config team a couple of weeks ago, and talked about the [service initiation page]( http://wet-boew.github.io/themes-dist/GCWeb/service-en.html), among other things.  The group decided that it would be best to get rid of the horizontal lines down in the “other ways to apply” area near the bottom.  That information is currently marked up as a definition list, and that’s where it’s getting the dividing lines from.  Could you adjust the styling so that definition lists don’t display horizontal lines between each DT/DD pair?

I’m guessing that definition lists aren’t yet used extensively in the GCweb theme, so changing the default styling probably wouldn’t be destructive.  And I’m also guessing that even on proper DL pages (like glossaries) that the dividers aren’t necessary, that they’re just adding unnecessary noise.  But - I am just guessing here.  So if you think it would be safer to leave the CSS as it is now, maybe you could instead find some other suitable way to mark up the “other ways to apply” area?

Up to you, and the rest of the WET team.  I'd be inclined to just change the styling of all DLs to remove the lines, but if you'd prefer to just change the markup of the service initiation page, that would work too.

**Comment by cfarquharson** [comment]
I actually like the horizontal line for a `dl-horizontal` especially when using it in a glossary or something like that.  That said, the way you have it on the service initiation page for phone numbers and addresses makes me question if that's actually a 'definition'.  Couldn't you just use normal grids for that content and then you wouldn't get the horizontal lines, plus it would be a bit more semantically correct.

**Comment by shawnthompson** [comment]
The horizontal line is there because of a closed issue, don't have the time to look for it but it's in WET. It helps readability. I will remove it from this template page because it makes sense. We are using 'dl' for semantics. In the same way we are using it for date modified. The numbers define the term to the left, therefore semantically it makes sense. We could even add multiple 'dd' if we have multiple numbers.

**Comment by shawnthompson** [comment]
Here's the commit where the border was added

https://github.com/wet-boew/wet-boew/pull/6842
