### ISSUE TITLE
"Follow" icons are trimmed on left and right sides.

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/GCWeb#1194]
I bring this to your attention in case it's a more wide-spread problem than just with a BlackBerry Z30 (BB10 OS).  On any page that has the "followus" section at the top, the icons for the various services are not shown to their full widths (see image below).

![bbz30-followus](https://cloud.githubusercontent.com/assets/1347487/20331011/a3d0fe24-ab70-11e6-8fa3-4757657b869c.png)

I can't reproduce this with the developer tools in a desktop web browser.  I've only seen it on the device itself.

**Comment by EricLavoie88** [comment]
I also have this issue on my Blackberry Classic running Blackberry 10 OS.

**Comment by RobJohnston** [comment]
Support for the BB10 OS ends today, so I'm closing this.
