### ISSUE TITLE
Tabbed Interface - Carousel: Accessibility: carousel: Link focus

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/GCWeb#1201]
Carousels in Canada.ca theme are missing the focus on the image links.

cc: @rlambert27

**Comment by duboisp** [comment]
have you tested with the latest wet-boew dev release? The merged PR https://github.com/wet-boew/wet-boew/pull/7683 fix various issue with the carousel focus. Although it will be only released with version 4.0.24

**Comment by LaurentGoderre** [comment]
I reinitiated a build for GCWeb so it will take the latest changes from WET

**Comment by LaurentGoderre** [comment]
Check again

**Comment by duboisp** [comment]
I tested and the focus is not showed for the [GCweb theme](http://wet-boew.github.io/themes-dist/GCWeb/demos/tabs/tabs-carousel-en.html) but it work for [wet-boew theme](http://wet-boew.github.io/wet-boew/demos/tabs/tabs-carousel-en.html).

I think there is some styling adjustment in GCWeb that needs to be completed.

@shawnthompson you may found how to fix it by looking of what have been modified by the PR wet-boew/wet-boew#7683

**Comment by LaurentGoderre** [comment]
The theme shouldn't be interfering with the PR....

**Comment by LaurentGoderre** [comment]
@duboisp can you test again? The examples were updated in GCWeb

**Comment by duboisp** [comment]
@LaurentGoderre it's work for me.
