### ISSUE TITLE
Topic page without social media, alert or image

### ISSUE THREAD

**Issue by MichaelDalrymple** [wet-boew/GCWeb#1202]
With the release of the IA Spec 1.3.2, I'm wondering what a theme/topic page should look like when newly optional components such as the social media bar, the alert box and the upper-right topic page are removed. Not sure if "Most requested" is supposed to appear above "Services and information" or if the top section is supposed to justify. Wondering if someone could send me screenshots of what the page should look like to michael.dalrymple@canada.ca for the following scenarios (1) no image, no social media bar, no alert box, (2) just social media bar, (3) just alert bar. Thanks.

**Comment by DK-TBS** [comment]
Hi Michael!  I'll try to post them here, so any others who may be reading the convo can follow along.  Not much special work involved in removing those elements, the page template looks about as you would expect it to when those pieces are removed.  The only change I made was to stretch the top left column (the one with the intro) across to 75% width, when the photo isn't there on the right side.  Seems a little more comfortable that way  :)

Not sure why that alert is there on the topic page template... that's the one that usually appears on the institutional profile pages, for organizations that have already moved some of their content over to the new site.  But if ever there was a topic-wide alert placed on a topic page, then that is where it would go.

![topic - all elements](https://cloud.githubusercontent.com/assets/9662127/20847972/396ffb8a-b89e-11e6-9088-ae63cf59ae6b.jpg)

![topic - few elements](https://cloud.githubusercontent.com/assets/9662127/20847987/3f609bda-b89e-11e6-9107-d251099ef75f.jpg)

![topic - social only](https://cloud.githubusercontent.com/assets/9662127/20847993/436b946e-b89e-11e6-8d49-e96ef159a77c.jpg)

![topic - alert only](https://cloud.githubusercontent.com/assets/9662127/20847998/4801bb16-b89e-11e6-9307-e678a4667d52.jpg)

**Comment by MichaelDalrymple** [comment]
That's great. Thanks for this. My next question is, will the code in the WET templates be updated to indicate (in the actual code) where each of these optional elements starts/ends so that that section of code can be removed when not in use? Or are there instructions somewhere on what code to modify to get the pages to look like this?

**Comment by DK-TBS** [comment]
Not to my knowledge.  I'm guessing that the team configuring the AEM solution will just let the platform automatically deal with that kind of thing.  In the meantime, those of us working with the templates the old fashioned way will have to peek under the hood and find the right spots to tweak.  It's pretty straightforward though, any web developer will be able to find the right blocks and rip them out.   Easy tweaks.

**Comment by zzucco** [comment]
Can this issue be closed?
