### ISSUE TITLE
"Report a problem or mistake on this page" - some content on French page is in English

### ISSUE THREAD

**Issue by biljanap** [wet-boew/GCWeb#1210]
There are multiple instances in “Signaler un problème ou une erreur sur cette page” section where English is used instead of French.
All value attributes for <input> elements have English content.

Examples:
```html
<label for="problem1">
     <input type="checkbox" data-reveal="#broken" name="problem" value="Something is broken" id="problem1">
     Quelque chose ne fonctionne pas
</label>
```
```html
<label for="problem2">
     <input type="checkbox" data-reveal="#spelling" name="problem" value="It has a spelling or grammar mistake" id="problem2">
      Il y a une erreur d&#39;orthographe ou de grammaire
</label>
```

**Comment by zzucco** [comment]
I'm not quite sure what the problem is. For checkboxes, the value attribute is not something ever displayed to the user.
Since this issue was posted, all the value tags have been changed to "Yes".
If no further information is provided, I will consider this issue resolved.
