### ISSUE TITLE
Content page - Signed On (class usage issue)

### ISSUE THREAD

**Issue by thekodester** [wet-boew/GCWeb#1219]
So currently the `Signed in as...` is using `<p class="btn">` and kinda acts like a button a bit when hovering over the text with a mouse maybe it should be changed to `<p style="display: inline-block;">` or the `wb-so` css id update to that styling.

URL: http://wet-boew.github.io/themes-dist/GCWeb/content-signedon-en.html

**Comment by LaurentGoderre** [comment]
Hmmm, Bootstrap should have a class to line up text with buttons, that is why the btn class was used.

**Comment by thekodester** [comment]
Looks like some has update the code on the page.
