### ISSUE TITLE
Application templates (secure / non-secure) - Community review

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/GCWeb#1223]
Good afternoon!

**Background**

ESDC is moving all its secure applications to use the CDTS (content delivery templates solution) by the new fiscal year. As such, we have done a lot of work with the secure applications to implement the Canada.ca template.

The transactional scenario captured in the C&IA specs does not fully reflect the requirements of our secure service applications, so we are proposing some tweaks. 

As we were documenting all the requirements for both secure and non-secure applications it became clear their business needs were not being met as it relates to navigation patterns, particularly in regards to our service portals where there is a lot of content. ESDC's e-Account user experience team have worked with us to ensure the Canada templates meet the needs of secure applications. 

Moving forward we will be proposing changes to the spec where needed to address the needs of not only ESDC applications but also help other institutions. With this effort, we hope to help e-Account achieve its goal of consistent user experience across service applications, and remain in sync with the best practices for usability that e-Account is championing. We also hope this will help other institutions facing the same issues.

**CDTS information**

Our current [GCPedia page](http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_(CDTS)) is being revamped and will be launched within a couple of weeks. Our original page was done quickly to help other institutions register and obtain more information. However with the dramatic increase in usage it's clear that our current GCPedia page does not meet the needs of our users. Stay tuned for a better looking GCPedia page!

At the end of 2016 the CDTS had reached over 1 billion hits on our combined Akamai and ESDC servers!

**Application templates**

You can consult the various scenarios at the following URL:

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_23/cdts/appTop/apptop-en.shtml

The page contains both the GCWeb theme and the intranet.canada.ca themes. The different scenarios display one option that is available but any of the scenarios can be mix and matched to obtain the desired look and feel. 

At this point we're looking for feedback from the community on the templates. We are making lateral announcements as well to TBS and to Principal Publisher looking for feedback. 

As ESDC is the first to apply the Canada templates to its secure applications, we hope the work we have done will be useful for other institutions in future. 

Thoughts? Any and all feedback welcome!

**Comment by shawnthompson** [comment]
cc/ @lucas-hay @DK-TBS @masterbee @LaurentGoderre @TouficS @pcwsmith

**Comment by LaurentGoderre** [comment]
I"m not sure how visible the application name is at the top. Many user may ignore the top part since it looks like it's always the same.

**Comment by pittar** [comment]
Having the CDTS code on GitHub would be a fantastic help.  We can't use the "stock" library because it's JSP based (we use Thymeleaf), so we have to reverse engineer it.  It would also make finding the deltas much easier.

I imagine anybody that is invested in JSF or Velocity (or any other non-JSP variant) would be interested in this as well.

**Comment by rlambert27** [comment]
@pittar Hi Andrew, actually Calvin and Pierre are actually putting their code up on Gitlab:

http://gitlab.ssc.etg.gc.ca/GOCWebTemplates

JAVA templates are not up yet but I believe Calvin said they were working on that.

**Comment by pittar** [comment]
@rlambert27 , fantastic!  Thanks.  That will be very helpful.

**Comment by RobJohnston** [comment]
I kind of agree with @LaurentGoderre that the application name at the top won't be visible, and for the same reason.  

Consider how a sub-site is done on the intranet theme.  For example, http://wet-boew.github.io/themes-dist/theme-gc-intranet/content-subsite-en.html

**Comment by DK-TBS** [comment]
TBS and ESDC have been working together to update the design of these templates, to bring them more in line with the templates already established for Canada.ca and for "transactional scenarios".  Best to hold off on reviewing or commenting on the new templates until the updated design is ready.  Not sure how long it's going to take, but we're all working on it as fast as we can, we know there's a big demand for this stuff.  Stay tuned!

**Comment by rlambert27** [comment]
I'll create a new review thread once we've got the updated designs.

**Comment by bchagnon** [comment]
On the GCPedia page, shouldn't num. 8 option of the decision tree read "custom header/footer" and not "default"?

> 8 - GCIntranet / version - Application - Target : You want to implement the intranet.canada.ca with the **custom** header/footer and you want to test any new changes that are released

**Comment by shawnthompson** [comment]
@bchagnon Thank you very much for letting us know. This has now been corrected.

For further issues with CDTS, look up our repository on GCCode (/sgdc-cdts/sgdc-cdts).

I don't want to share the link here because it's internal to our firewall.

If you can't find it, send me an email and I'll send you the link.
