### ISSUE TITLE
RE: Added section Focus on to homepage

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#1233]
@MaximMartel 

[https://maximmartel.github.io//GCWeb-UpdateHomeEnFr/home-en.html](https://maximmartel.github.io//GCWeb-UpdateHomeEnFr/home-en.html)

[https://maximmartel.github.io//GCWeb-UpdateHomeEnFr/home-fr.html](https://maximmartel.github.io//GCWeb-UpdateHomeEnFr/home-fr.html)

These look pretty good, but we should probably put the placeholder "Audience" labels in square brackets, to be consistent with the rest of the spec templates - "[Audience]". We always try to mark placeholder text in square brackets like that to distinguish it from mandatory labels.

Also, on the French side, the French version of the spec seems to have "Public cible" as the placeholder label, instead of just "Public". So we should probably go with "[Public cible]".

**Comment by MaximMartel** [comment]
@DK-TBS  On it my good sir !

**Comment by MaximMartel** [comment]
@DK-TBS https://maximmartel.github.io/GCWeb-UpdateFocusonAudience/home-fr.html | https://maximmartel.github.io/GCWeb-UpdateFocusonAudience/home-en.html

**Comment by shawnthompson** [comment]
Thanks @DK-TBS
