### ISSUE TITLE
Overlay lightbox background

### ISSUE THREAD

**Issue by UXaaron** [wet-boew/GCWeb#1258]
Would like semi-transparent option (50%?) for the background behind overlay window used in "Centred popup (Lightbox)" and "Centred popup - Modal (Lightbox + Modal)". I want users to know that they are still on their primary task page yet retain their focus on overlay window.

To give some context, TBS (myself and @DK-TBS) is preparing section in Content & IA Spec advising use of the overlay windows for privacy notices, disclaimer links, etc. Looking at @lucas-hay and @masterbee for help, please :)

**Comment by RobJohnston** [comment]
I just saw an answer to why this cannot be done a couple days ago in https://github.com/wet-boew/wet-boew/issues/8044#issuecomment-306572667.

**Comment by DK-TBS** [comment]
@RobJohnston:  I saw that other thread, and it made me think of this one, too.  I can understand why the blacked-out page has to be completely blacked out for modal dialogs, but - do we face the same limitation for non-modal lightbox popups?  Can we go 50% grey on those and leave the modal ones completely black?

**Comment by DK-TBS** [comment]
@UXaaron:  Sounds like we're out of luck on this one.  Apparently screen readers run into the same problem here as they did with the modal pop-up, so we're not going to be able to get away with letting the background/page show through without sucking screen readers into a trap  :(

[https://github.com/wet-boew/wet-boew/issues/8044#issuecomment-307200197](https://github.com/wet-boew/wet-boew/issues/8044#issuecomment-307200197)

**Comment by DK-TBS** [comment]
@UXaaron - Hey Aaron:  have you considered using the "middle screen overlay"?  It doesn't darken the background at all, but maybe that's just fine?

[https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html](https://wet-boew.github.io/v4.0-ci/demos/overlay/overlay-en.html)

**Comment by UXaaron** [comment]
@DK-TBS I have considered it. I'm not sure what the accessibility issues might be for not darkening the background primary window. I would think it might be confusing for vision impaired people.

**Comment by DK-TBS** [comment]
As I understand it, they only managed to keep the screen readers from wandering away from the dialog box by slapping a display:none on the entire background, on the rest of the page.  So the overlay can be white or black or beige, but we can't show the page.  I don't know anything about the details of the problem, though...

**Comment by kodecount** [comment]
Changing transparency wouldn't work with a modal + lightbox as their is a secondary rule called [lightbox-modal-hide](https://github.com/wet-boew/wet-boew/blob/eb432eeef3a23e6e7a0e930315b2a3d039b09d94/src/plugins/lightbox/_base.scss#L14) this CSS rule hides the content of the page. Which is why it is so dark.

**Comment by RitchieD** [comment]
Note:   AJAXed content is not hidden when modal popup is active.  Making a half hidden background.

For anyone who really can't stand the full-blackout here is an unsupported un-recommend band-aid.

Comment out the code that adds the class "wb-modal" to the body.

wet-boew.min.js :
`for(/*o.find("body").addClass("wb-modal"),*/o.find(n).attr("aria-hidden","true")`

 wet-boew.js
`/*$document.find( "body" ).addClass( "wb-modal" );*/`

**Comment by zzucco** [comment]
If we won't be able to implement this, we should close this issue.

**Comment by DK-TBS** [comment]
Ah, close it
