### ISSUE TITLE
template plugin poyfill for IE-11

### ISSUE THREAD

**Issue by sgdowney** [wet-boew/GCWeb#1261]
Is the template.js polyfill for the `<template>` tag bundled in another js file or is it supposed to be separate.  The template.js file doesn't appear to be part of the GCWeb distribution package.

**Comment by duboisp** [comment]
template.js is a polyfill for the ```<template>``` tag in IE. It is this file: https://github.com/wet-boew/GCWeb/blob/master/src/plugins/deps/template.js
Yes it should be included in the build.  I will look to fix it.
