### ISSUE TITLE
"Share this page" link no longer using 100% width in extra small views.

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/GCWeb#1268]
In most of GCWeb's page templates, the share widget plugin is used to inject a "Share this page" link at the bottom of the content area. In small view and over, that link is floated to the right. In GCWeb 4.0.25 and under, it uses a width of 100% in extra small views.

Unfortunately, the aforementioned 100% width behaviour relied on a CSS selector that was recently removed in wet-boew/wet-boew#8076. The specific selector GCWeb relied on was formerly situated on [line 554 of src/base/bootstrap-overrides/_base.scss](https://github.com/wet-boew/wet-boew/pull/8076/files#diff-93656052841a8c39fc075d98b607fb71L554).

I can think of 3 potential ways of resolving this, but all have their own drawbacks...

**Possible solutions:**
* Revert all or part of wet-boew/wet-boew#8076. The overrides it removed were first introduced in early 2014 via wet-boew/wet-boew#4206 to fix wet-boew/wet-boew#4191. So it can probably be safely assumed that in practically all WET 4.0.x implementations until now, content was coded and tested with those overrides in mind. The overrides probably shouldn't of been introduced in the first place, but by now they've been around for so long that suddenly removing them might cause unexpected issues across pre-existing content pages.
* Add the ``col-xs-12`` class to the share widget's parent ``div`` element. The downside of this would be that it would necessitate an HTML markup change in all pre-existing GCWeb implementations to retain a layout that was already working before.
* In [src/share/](https://github.com/wet-boew/GCWeb/blob/master/src/share), add a "_screen-xs-max.scss" file containing a selector that sets ``float: none !important;`` on any ``pull-right`` classes that are children of the ``pagedetails`` class. The drawbacks of this are that it's kind of hacky and can't explicitly target the share widget's parent ``div``.

@lucas-hay @thomasgohard Thoughts?

**Screenshots:**
* **GCWeb 4.0.25 and under:**
![gcweb-share-before](https://user-images.githubusercontent.com/1907279/28089790-259e1bb0-6658-11e7-9b2e-78747a9f762e.png)
* **GCWeb 4.0.26-development (as things stand right now):**
![gcweb-share-after](https://user-images.githubusercontent.com/1907279/28089793-2c3ec550-6658-11e7-9ab3-2268bd88318e.png)

**Comment by duboisp** [comment]
I am more for re-implementing the override but before investigate what issue their removal were solving.

**Comment by EricDunsworth** [comment]
@duboisp The overrides wet-boew/wet-boew#8076 reverted were first introduced in wet-boew/wet-boew#4206 to address wet-boew/wet-boew#4191

**Comment by thomasgohard** [comment]
I looked at the code for that part of the template and it's not implementing the grid correctly. The share widget should be moved to the right using offsets: http://getbootstrap.com/css/#grid-offsetting. The pull-right was never intended for this purpose and is not part of the grid.

The whole 'pagedetails' segment should be replaced:
```
<div class="row pagedetails">
    <div class="col-sm-6 col-lg-4 mrgn-tp-sm">
        <a href="https://www.canada.ca/en/report-problem.html" class="btn btn-default btn-block">Report a problem or mistake on this page</a>
    </div>
    <div class="col-sm-3 mrgn-tp-sm pull-right">
        <div class="wb-share" data-wb-share='{"lnkClass": "btn btn-default btn-block"}'></div>
    </div>
    <div class="datemod col-xs-12 mrgn-tp-lg">
        <dl id="wb-dtmd">
            <dt>Date modified:&#32;</dt>
            <dd><time property="dateModified">2014-02-19</time></dd>
        </dl>
    </div>
</div>
```
should be
```
<div class="pagedetails">
    <div class="row">
        <div class="col-sm-6 col-lg-4 mrgn-tp-sm">
            <a href="https://www.canada.ca/en/report-problem.html" class="btn btn-default btn-block">Report a problem or mistake on this page</a>
        </div>
        <div class="col-sm-3 mrgn-tp-sm col-sm-offset-3 col-lg-offset-5">
            <div class="wb-share" data-wb-share='{"lnkClass": "btn btn-default btn-block"}'></div>
        </div>
    </div>
    <div class="row">
        <div class="datemod col-xs-12 mrgn-tp-lg">
            <dl id="wb-dtmd">
                <dt>Date modified:&#32;</dt>
                <dd><time property="dateModified">2014-02-19</time></dd>
            </dl>
        </div>
    </div>
</div>
```

**Comment by duboisp** [comment]
Thanks @thomasgohard 

Just a proposition for an interim solution:
I don’t know how template markup change is disseminated, but if that is a challenges for institution to implement then an interim solution could be to add a temporary custom CSS, scoped only for the `.pagedetails`, that simulate the effect and then we can go ahead with implementing Thomas solution. That before the next release.

**Comment by EricDunsworth** [comment]
@thomasgohard @duboisp I agree that the current markup isn't ideal. But aren't WET/GCWeb's maintenance releases supposed to be restricted to non-breaking changes?

If a pre-existing GCWeb 4.0.25 or older implementation uses the old ``pagedetails`` markup, then updates to 4.0.26 and beyond, shouldn't there be an expectation that their "Share this page" links will continue to use 100% width in extra small view and lower, without any need for HTML markup changes? I know there's precedent for markup changes in maintenance releases due to factors that went beyond WET's control (like the feeds plugin losing Twitter/Facebook support), but in this case, the factors at play are fully in WET's control.

Apart from that, I agree with @thomasgohard's proposed ``pagedetails`` markup changes. But if we went in that direction, I think it'd be worth going a step further by eliminating the second row and grid column (since nothing else exists on the same line as "Date modified:"). The ``datemod`` class could also be removed. The end result would leave ``pagedetails`` looking virtually identical to how it currently looks, with the only difference being slightly fewer pixels'-worth of space above and below "Date modified:" (although that could be adjusted to look identical to the status quo by adding a CSS selector to adjust the CSS properties of ``wb-dtmd`` IDs that are direct descendants of the ``pagedetails`` class).

**HTML example:**
```
<div class="pagedetails">
    <div class="row">
        <div class="col-sm-6 col-lg-4 mrgn-tp-sm">
            <a href="https://www.canada.ca/en/report-problem.html" class="btn btn-default btn-block">Report a problem or mistake on this page</a>
        </div>
        <div class="col-sm-3 mrgn-tp-sm col-sm-offset-3 col-lg-offset-5">
            <div class="wb-share" data-wb-share='{"lnkClass": "btn btn-default btn-block"}'></div>
        </div>
    </div>
    <dl id="wb-dtmd">
      <dt>Date modified:&#32;</dt>
      <dd><time property="dateModified">2014-02-19</time></dd>
    </dl>
</div>
```

@duboisp I agree with your proposal, but think the temporary CSS hack should be permanent in 4.0.x to avoid forcing HTML markup changes onto any pre-4.0.26 implementations. I don't think it'd be appropriate to remove the hack until GCWeb 4.1 or higher.

**Comment by lucas-hay** [comment]
Leaving this open so we don't forget to fix markup.
