### ISSUE TITLE
Application templates - Community review #2

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/GCWeb#1286]
Good morning!

Background

As discussed a bit in wet-boew/GCWeb#1283 the ESDC WS CoE has been working with TBS, Portfolio Web (ESDC) and the MSCA UX team (ESDC) to develop a second version of the application templates.

The templates have gone through multiple iterations and reviews by all groups involved and we're now ready for community review. 

CDTS information

For the period from January 2017 to June 2017 the CDTS had reached over 2.8 billion hits on our combined Akamai and ESDC servers! The CDTS solution is being used by over 20 federal departments.

Application templates

You can consult the various scenarios at the following URL:

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_26/cdts/appTop/apptop-en.shtml

The page contains both the GCWeb theme and the intranet.canada.ca themes. The different scenarios display one option that is available but any of the scenarios can be mix and matched to obtain the desired look and feel.

At this point we're looking for feedback from the community on the templates.

Thoughts? Any and all feedback welcome!

cc/ @lucas-hay @DK-TBS @masterbee @LaurentGoderre @TouficS @pcwsmith @shawnthompson @EricDunsworth

**Comment by nschonni** [comment]
The GCIntranet pages don't appear to work. Most of the files return a 404, so the page looks unstyled

**Comment by rlambert27** [comment]
This review is for GCWeb but i'll fix the GCIntranet sample pages tomorrow, they are pointing to our ESDC internal server.

**Comment by rlambert27** [comment]
@nschonni GCIntranet templates should be all good now, thanks for pointing that out!

**Comment by nschonni** [comment]
@rlambert27 just tried from home, and they're still looking unstyled to me

**Comment by rlambert27** [comment]
Sorry we pushed out v4.0.26 and it still had the old code in the sample files. I've updated the files and the samples are also now on v4.0.26.

**Comment by RobJohnston** [comment]
@rlambert27 So for the GCIntranet theme, the [standard footer](https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_26/cdts/appTop/appfooter-en.shtml) and the [transactional footer](https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_26/cdts/appTop/appfooter_transactional-en.shtml) are identical pages, or am I missing the difference?

**Comment by rlambert27** [comment]
No difference, I've removed that last scenario, it's a leftover when the custom footer was different. TBS changed it so it had no links in the footer for the terms and privacy links.

**Comment by steve-h** [comment]
@rlambert27  I like the look of the Application templates.  Is the CDTS going to be open source?

I cannot fully see the CDN environment setup.  I have many javascript suggestions.  The initial pageloads are slower due to wet-en.js having to round trip before the jquery load is started for instance.

**Comment by rlambert27** [comment]
The CDTS is an open solution that anybody can use currently with no need to register. This could change in the future.

The CDTS code however is not open source and is hosted in GoC Gitlabs.

For the JS suggestions are you talking about JS that is in WET or the JS that is used in the CDTS. Our solution simply makes it easier to consume WET and the GCWeb/GCIntranet themes, we don't change any core WET code.

If the JS is related to the CDTS please open a ticket here : https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues

**Comment by rlambert27** [comment]
I'm going to close this issue since the templates have been approved and are already being used in multiple departments. Any feedback or comments can be redirected to the CDTS Gitlabs page here:

https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues
