### ISSUE TITLE
Buton name for Log out

### ISSUE THREAD

**Issue by sarumim** [wet-boew/GCWeb#1311]
Style guide is using Logout
http://wet-boew.github.io/wet-boew-styleguide/v4/design/buttons-en.html

Application template is using  Sign out
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_26/cdts/appTop/apptop_signout-en.shtml

Which one should be used?
Same with Login vs  Sign in

**Comment by cfarquharson** [comment]
Updated to say 'sign in' and 'sign' out instead of 'login' and 'log out'.  It will take a bit for the new build to show the changes.

**Comment by sarumim** [comment]
Thanks for confirmation and update

**Comment by cfarquharson** [comment]
@LaurentGoderre @nschonni I updated the files but the build never happened.  Do you know why?

**Comment by LaurentGoderre** [comment]
Wow! the build for that repo is severly outdated. It probably need to be updated for it to work.

**Comment by cfarquharson** [comment]
@LaurentGoderre is that something you can do? I don't know how to initiate that

**Comment by LaurentGoderre** [comment]
Eventually
