### ISSUE TITLE
Megamenu not linked in basic HTML version

### ISSUE THREAD

**Issue by bsouster** [wet-boew/GCWeb#1324]
The links in the megamenu on [Canada.ca](https://www.canada.ca/en.html?wbdisable=true#immigration) do not work in the basic HTML version.

**Comment by lucas-hay** [comment]
@bsouster are you correct and it is being looked at.
For future reference, Issue related to Canada.ca should be submitted to the prinicipal publisher service desk, not on github. This issue is strictly a Canada.ca issue, it is not related to the templates. 
Closing this issue on here.

**Comment by nschonni** [comment]
@lucas-hay it might help if you put that type of information into an ISSUE_TEMPLATE.md

**Comment by RobJohnston** [comment]
They haven't worked in a loooooooooooong time:  https://github.com/wet-boew/GCWeb/issues/1163
