### ISSUE TITLE
Canada.ca theme: alternate language template with CDTS?

### ISSUE THREAD

**Issue by Bgolden67** [wet-boew/GCWeb#1327]
Is there anything in the works or maybe something already in place but not linked to from the examples that will work with alternate languages other than eng/Fra?
Anything similar to these:
http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-nositemenubc-iu.html
http://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-nosearchlangsitemenubc-iu.html 

if not, how can we look into what is to be acceptable?

**Comment by shawnthompson** [comment]
@Bgolden67 presently CDTS only supports the English and French template but it might be something we could put into place in future releases. We started a repository on GCCode and I'll move this issue over to there. Search for sgdc-cdts on GCCode to find us. I'm not sure I want to link to the domain on here seeing as though it's an internet to GoC server.
