### ISSUE TITLE
Missing footer images v 27

### ISSUE THREAD

**Issue by mhutchis** [wet-boew/GCWeb#1333]
The three images:
http://cdn.canada.ca/gcweb-cdn-live/features/img/pi-2018-02-14-1.jpg
http://cdn.canada.ca/gcweb-cdn-live/features/img/pi-2018-02-14-2.jpg
http://cdn.canada.ca/gcweb-cdn-live/features/img/pi-2018-02-12-1.jpg
are not displaying (they are 404).

I believe they were there earlier today, but have since disappeared.

**Comment by nschonni** [comment]
Think this probably needs to be reported to https://gccode.ssc.gc.ca/sgdc-cdts/sgdc-cdts/issues instead
