### ISSUE TITLE
DataJSON not rendering on example page

### ISSUE THREAD

**Issue by nschonni** [wet-boew/GCWeb#1339]
None of the examples appear to be running on http://wet-boew.github.io/themes-dist/GCWeb/demos/data-json/template-en.html
Maybe there is an issue copying the JSON example file since I'm not seeing a request for it in the Network panel of Firefox 59.0.1 on OSX

**Comment by duboisp** [comment]
Thanks @nschonni ,

I saw there is some dependencies that are missing. I would need to update the build script.
