### ISSUE TITLE
Sign in / Sign out  or Login Logout which is correct?

### ISSUE THREAD

**Issue by sarumim** [wet-boew/GCWeb#1354]
Following two templates use  Sign in / Sign out
https://wet-boew.github.io/themes-dist/GCWeb/content-signedoff-en.html

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_27/cdts/appTop/apptop_signin-en.shtml

Style guide uses Login / Logout
http://wet-boew.github.io/wet-boew-styleguide/v4/design/buttons-en.html

Does this mean either is fine to use?

**Comment by thomasgohard** [comment]
It should be sign in / sign out.

A change was made last November to update the style guide (https://github.com/wet-boew/wet-boew-styleguide/commit/74d81b16264e906f091566a65af7eb728e7273ab). However, the build for this repository is broken so none of the updates made in the last six months are reflected. This issue has been flagged: https://github.com/wet-boew/wet-boew-styleguide/issues/352.

**Comment by sarumim** [comment]
Thank you for your reply.  Would you like me to close this @thomasgohard

**Comment by thomasgohard** [comment]
Closing as resolved.

**Comment by nschonni** [comment]
The live styleguide is correct again
