### ISSUE TITLE
GCWeb v2: "cnt-wdth-lmtd" overrides "mrgn-bttm-*" classes

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/GCWeb#1486]
I've noticed that in [limited width content pages](https://wet-boew.github.io/themes-dist/GCWeb/content-limit-en.html), [WET's margin-bottom utility classes](http://wet-boew.github.io/wet-boew-styleguide/v4/design/proximity-en.html#design) aren't working. This might potentially cause issues for implementers that need to adjust or disable bottom margins on a specific piece of content.

What seems to be happening is that the [``cnt-wdth-lmtd`` class' SCSS selectors](https://github.com/wet-boew/GCWeb/blob/master/src/_defaults.scss#L54-L80) are more specific than the [``mrgn-bttm-*`` ones](https://github.com/wet-boew/wet-boew/blob/master/src/base/proximity/_base.scss#L168-L186). The end result in that the latter classes are unable to take effect.

As for possible solutions... I can think of a few, but IMO none are very elegant:
* Use a ``:not()`` pseudo-class in all of the ``cnt-wdth-lmtd`` SCSS selectors that override margin-bottom.
* In WET, turn the ``mrgn-bttm-*`` classes' values into variables and re-use them in GCWeb-specific overrides.
* Add ``!important`` to the end of all of the [affected selectors in wet-boew/wet-boew/src/base/proximity/_base.scss](https://github.com/wet-boew/wet-boew/blob/master/src/base/proximity/_base.scss#L168-L186).

**HTML code sample:**
```html
<p class="mrgn-bttm-0">Paragraph 1</p>
<p>Paragraph 2</p>
```

**Output in a [normal GCWeb content page template](https://wet-boew.github.io/themes-dist/GCWeb/content-en.html):**

![p-mrgn-bttm-0_normal](https://user-images.githubusercontent.com/1907279/51342621-5e234e00-1a62-11e9-9e6d-98e5bc86d02a.png)

**Output in [GCWeb's limited width content template](https://wet-boew.github.io/themes-dist/GCWeb/content-limit-en.html):**

![p-mrgn-bttm-0_cnt-wdth-lmtd](https://user-images.githubusercontent.com/1907279/51342624-5f547b00-1a62-11e9-9962-84d3f429416e.png)

CC @duboisp

**Comment by duboisp** [comment]
@patlaj is the additional spacing for paragraph and list are essential for pages with the limited width content?

**Comment by patlaj** [comment]
I'm not really sure that we need cnt-wdth-lmtd as a class, which would eliminate this problem. Really, we want to specify that any line of text that goes beyond a reasonable maximum should be constrained. In the extreme case that someone actually needs 100 characters of text on a line, then it's *then* that they should have to use a custom class. Not the default. 

For example, here's an illustration we used recently to demonstrate the impact to someone:

![screen shot 2019-01-18 at 10 35 30 am](https://user-images.githubusercontent.com/1799919/51396519-33da9a80-1b0d-11e9-8907-611ae7959d25.png)

The point of that is just to show that the layouts aren't affected. 

I know that's not quite the question at hand, but wonder if this shift in how we approach the limited width might solve this kind of problem?

Tagging @jmealing

**Comment by duboisp** [comment]
Thanks @patlaj , I passed on your comment to the responsible team.

**Comment by duboisp** [comment]
For now, I will remove the custom bottom margin that can't be overwritten for pages with the limited width content. We will adjust later the spacing or/and apply the limited width content style by default.

**Comment by EricDunsworth** [comment]
Gonna close this out since IMO #1488 resolved it.

@duboisp Thanks :)!
