### ISSUE TITLE
Social Media - Remove GooglePlus in the template/working example

### ISSUE THREAD

**Issue by duboisp** [wet-boew/GCWeb#1518]
Google plus are going to be offline soon, Remove it from the social (follow us) template but keep the icon in the CSS until the next or second next major version. 

Add a commend beside this CSS image saying it is deprecated: https://github.com/wet-boew/GCWeb/blob/49ba930d002a5a584b8f416959f7455a183e058e/src/social-media-icons/_base.scss#L47

**Comment by GormFrank** [comment]
This can be assessed now.
