### ISSUE TITLE
Wrong links to Content and IA specs

### ISSUE THREAD

**Issue by quidampepin** [wet-boew/GCWeb#1525]
On https://wet-boew.github.io/themes-dist/GCWeb/index-en.html, links in the Specification column point to the old version of the specs. All templates and patterns are now on design.canada.ca and conception.canada.ca (in a GitHub repo), accessible through the library: https://www.canada.ca/en/government/about/design-system/pattern-library.html 

For example, the link to the Theme page is:
https://design.canada.ca/mandatory-templates/theme-pages.html

instead of: 
https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/templates-detailed-specifications/theme-pages.html 

Could this be fixed?

**Comment by duboisp** [comment]
@quidampepin you can send a PR that would fix those link.

Here the corresponding files:
* https://github.com/wet-boew/GCWeb/blob/master/site/pages/index-en.hbs
* https://github.com/wet-boew/GCWeb/blob/master/site/pages/index-fr.hbs
