### ISSUE TITLE
How to get access to specific department search from the search box in the header?

### ISSUE THREAD

**Issue by samittal86** [wet-boew/GCWeb#1544]
I want to access search results specific to a department when someone add a keyword in the search box, similar to IRCC https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada.html. 
Where can I get the link to connect the search box with the department specific search results?

**Comment by duboisp** [comment]
@samittal86 Please ask the Principal Publisher service desk. You might need to ask your departmental theme lead to open the ticket on your behalf.

**Comment by GormFrank** [comment]
Hi @samittal86 If you managed to get what you wanted, please feel free to close this issue. Thank you!

**Comment by samittal86** [comment]
Not needed anymore.
