### ISSUE TITLE
main .btn-primary

### ISSUE THREAD

**Issue by jkshapiro** [wet-boew/GCWeb#1554]
Hi there,

The file [src/buttons/_base.scss](https://github.com/wet-boew/GCWeb/blob/ed6c1aa6d59f74fa9fd29ec3b34a4dc38c5a7cf7/src/buttons/_base.scss) contains the following SCSS declaration:

```
main {
	.btn-primary {
		background-color: $accent-blue;
		border-color: $accent-blue;
	}
}

```
Why would we want primary buttons to look different inside the &lt;main&gt; element of a page?

**Comment by jkshapiro** [comment]
Have proposed https://github.com/wet-boew/GCWeb/pull/1555 to fix this

**Comment by EricDunsworth** [comment]
Closing this since #1555 was merged a few days back.

@jkshapiro FYI you might want to consider using [this syntax](https://help.github.com/en/articles/closing-issues-using-keywords) in future PRs so their associated issues can be auto-closed upon merging.
