### ISSUE TITLE
Bypass block colour

### ISSUE THREAD

**Issue by nicolasraymond** [wet-boew/GCWeb#1592]
This is only an esthetic thing but it seems the bypass blocks are the old blue colour, not the new menu/footer colour.

**Comment by duboisp** [comment]
@patlaj

**Comment by duboisp** [comment]
PR related #1587

**Comment by nicolasraymond** [comment]
yes, Canada.ca

**Comment by GormFrank** [comment]
@delisma

**Comment by delisma** [comment]
Yes, we can all agree to this.
