### ISSUE TITLE
CDN not responding

### ISSUE THREAD

**Issue by matdes** [wet-boew/GCWeb#1616]
Seems the cdn.canada.ca link for the menu is broken.

I cannot reach:
[https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-v5-en.html](https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-v5-en.html)
[https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-v5-fr.html](https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-v5-fr.html)

Can anyone else confirm if it is down?

**Comment by duboisp** [comment]
@matdes thanks for reporting, we are looking at it.

**Comment by duboisp** [comment]
@matdes the CDN link is now working,

FYI - We, Principal Publisher, are looking for an alternative solution. The URL might change in a near future.
