### ISSUE TITLE
Keeping the Advanced Search in the new template for search results

### ISSUE THREAD

**Issue by coprisanu** [wet-boew/GCWeb#1632]
Hi,

We want it to see how much is being used the Advanced Search. Our Analytics group has created a report comparing the Basic Search and Advanced Search.
The report is for the period of time July 01 - December 31, 2019
                                               Canada.ca   Search-Rechercher.gc.ca  Recherche-Search.gc.ca
Count of basic search             23,304,813   2,225,317                         3,813,633
Count of advanced search      782,470        220,629                            75,430
% of Searches with Adv. Search   3.36%         9.91%                               1.98%

There are a number of clients pointing their search box directly to the advanced search, the list is below
1. veterans.gc.ca
2. inspection.gc.ca
3. publicsafety.gc.ca
4. getprepared.gc.ca
5. getcybersafe.gc.ca
6. cyber.gc.ca
7. dec-ced.gc.ca

Seeing the number of searches leveraging the Advanced Search we suggest to keep the Advanced Search on the new [template ](https://wet-boew.github.io/themes-dist/GCWeb/search/index.html?wbdisable=true#wb-cont)for the search results. It could be in another location, at the bottom of the page like the news are using.

Thank you

**Comment by Borges-Porteous** [comment]
Keeping the advanced search form makes sense, particularly as an interim until we have new advanced search features such as the institution/theme filter and improved relevance measurement. It is, if nothing else, still what is used for those domains that Ryan mentioned, and we would not want to undermine that current, live use case.
 
However, as going to advanced search form from the standard search interface is very rare, this action can still be supported for those super users and those who scan a first page of results but can't find their relevant result, but moving it under the pagination. This will also help make the search input and following results design tighter and better, particularly in mobile view.

**Comment by namjohn920** [comment]
Added an advanced search link below the pagination tab.
check #1639

**Comment by duboisp** [comment]
@delisma

**Comment by GormFrank** [comment]
@duboisp Was there any discussion with @delisma on this?

**Comment by delisma** [comment]
@GormFrank There was a discussion about it in PR #1639 back in February. This seems to be the issue that triggered the PR.

**Comment by GormFrank** [comment]
Ok @delisma, so can this be closed then?

**Comment by delisma** [comment]
I would think so

**Comment by coprisanu** [comment]
Hi, Thank you for your help. Yes we can close it.
