### ISSUE TITLE
Canada.ca home page parsing error

### ISSUE THREAD

**Issue by bsouster** [wet-boew/GCWeb#1637]
The features don't pass parsing. (x2)

Error: Element p not allowed as child of element figure in this context. (Suppressing further errors from this subtree.)

**Comment by duboisp** [comment]
@GormFrank did a fix for this which consist to update the HTML template for the contextual feature.

**Comment by GormFrank** [comment]
It is officially part of GCWeb now and was released on Canada.ca. However, it is a design pattern, meaning that authors will have to change their institutional/theme/topic pages on their own to fix this. We will be handling the home page soon.

**Comment by GormFrank** [comment]
A ticket was opened with our team to tackle the home page. @EricDunsworth can you bring this up to your team for affected pages that belong to ESDC? Here is the documentation: https://wet-boew.github.io/themes-dist/GCWeb/component/gc-features-en.html. I can send a more formal email if you want. If so, should I send it to your team lead or the publishing team lead?

**Comment by EricDunsworth** [comment]
@GormFrank I'd recommend sending a formal email about it to both my team lead and the publishing leads.

My team isn't involved in maintaining those aspects of ESDC's pages. But we could potentially play a supporting role if there's a need to track down which exact ESDC pages are affected by that issue.
