### ISSUE TITLE
Filterable table bug with parenthesis in GCWeb5

### ISSUE THREAD

**Issue by Ferkner** [wet-boew/GCWeb#1648]
The filtering form on data tables always return 0 results when a drop-down has an item with parentheses selected, e.g. “Association of Southeast Asian Nations (ASEAN)”.

See example on https://canadabrandgocaccess.agr.gc.ca/members/000_filterable_datatable.html (only accessible if you are connected to a GoC network). For now we have had to remove the parenthesis and use dashes (http://www.agr.gc.ca/eng/international-trade-of-agri-food-products/market-intelligence/reports/?id=1522931721523). Encoding the parenthesis as &#40; and &#41; or &lpar; and &rpar; does not solve the issue.

This was not an issue previous on WET4.

Tested on IE11, Firefox 73 and Chrome 80.

**Comment by duboisp** [comment]
What I can see is the probably the parenthesis conflict with the [data table smart search](https://datatables.net/reference/api/search()) mode. Have you tried to escape the parenthesis in the value like we do for a regular expression?

Note: GCWeb5 is build on top of WET4. Technically the same issue can be reproduced with previous WET4.

**Comment by Ferkner** [comment]
We didn't think of that; didn't know that was an option. But I tried it and it works. Thank you for the solution!

**Comment by Ferkner** [comment]
It ended up working. It appears there was a content issue causing it. Thank you for your help!
