### ISSUE TITLE
GC Subway map navigation requires two H1s

### ISSUE THREAD

**Issue by jkshapiro** [wet-boew/GCWeb#1710]
Hi there,

The provisional feature "GC Subway map navigation" (https://wet-boew.github.io/themes-dist/GCWeb/provisional-en.html), as implemented, requires page authors to have two different `<h1>` elements on the page, with different styling. This is a contravention of the Canada.ca design system, which requires `<h1>` elements to have a particular styling, including a red line below (https://design.canada.ca/styles/typography.html).

A bigger issue, though, is that while it's legal to have multiple `<h1>`'s on a page, it's best practice not to. Some quotes:

WebAIM: https://webaim.org/techniques/semanticstructure/
> The `<h1>` describes the page as a whole (and should be similar to the page `<title>`). A page should typically have only one `<h1>`.

MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
> You should only use one `<h1>` per page. Using more than one will not result in an error, but using only one is seen as a best practice. It makes logical sense — `<h1>` is the most important heading, and tells you what the purpose of the overall page is. You wouldn't have a book with more than one title, or a movie with more than one name! Having a single top-level title is also arguably better for screenreader users, and SEO.

Can we change it to an `<h2>`?

**Comment by GormFrank** [comment]
Hi @jkshapiro, this discussion has already happened and was debated for quite some time, but in the end we collected all the evidences and made some in-depth research to come up with a strong design decision that explains the acceptance of having two H1s on a single page. I invite you to read it: https://wet-boew.github.io/wet-boew-documentation/decision/12.html. Also, I want to direct you to the references section at the bottom of it for all of the documentation surrounding the decision. 

If you want to argument against it, feel free to build a case that is stronger than this one, with all the documentation attached. Thank you!

**Comment by jkshapiro** [comment]
I did look through the discussion, and it does seem to cover my second concern. But what about the first one, the contravention of the Canada.ca Style Guide?
