### ISSUE TITLE
Possible Bug: Do action CSV download not rendering French characters (or commas for currency)

### ISSUE THREAD

**Issue by Christopher-O** [wet-boew/GCWeb#1714]
We have just implimented the csv do action function for our new calculator which is great, however we quickly determined that the calculator does not render French characters natively when the document is opened in Excel.  Apparently google docs is okay though.  If the file is opened in notepad and saved as ANSI, then opened in Excel it works.  Our in house IT added a fix in our custom code to render the download to open with French characters intact when opening directly in Excel.  
Something we were unable to fix was rendering French currency. The results came out odd (due to the nature of CSV itself)..so we had to render the French currency with decimals using more custom JS.  
We also originally tested this with a user who had Excel set to French settings, and they also were having issues importing the CSV file to render French characters or currency proprly.

**Comment by GormFrank** [comment]
@luc-bertrand-hrsdc Can you please look into this issue?

**Comment by duboisp** [comment]
for reference: https://github.com/wet-boew/GCWeb/blob/master/src/plugins/actionmng/actionmng.js#L209

**Comment by luc-bertrand-hrsdc** [comment]
Commited code to add a BOM at the beginning of the generated CSV content.  Tested working in MS-Excel 16.0.5044.1000

**Comment by luc-bertrand-hrsdc** [comment]
Fixed two unencoded html entities that were not rendering correctly from the wet-boew module

**Comment by luc-bertrand-hrsdc** [comment]
Closes #1714

**Comment by EricDunsworth** [comment]
Should this issue be closed?

I noticed @GormFrank added ``Closes #1714`` to #1723's OP yesterday. But that PR had already been merged a few days earlier, so the close syntax didn't close anything (only works if it's in place prior to merging a PR).

**Comment by GormFrank** [comment]
> Should this issue be closed?
> 
> I noticed @GormFrank added `Closes #1714` to #1723's OP yesterday. But that PR had already been merged a few days earlier, so the close syntax didn't close anything (only works if it's in place prior to merging a PR).

Yes @EricDunsworth I added that yesrterday. I know it didn't close the issue. I'm letting this sit for a while in order to let @Christopher-O close it or ask us to close it if he feels like it. If he doesn't, I will close the issue in a week or so.

**Comment by Christopher-O** [comment]
@GormFrank thanks for the follow up.  I'll close the issue. Thanks to everyone for your help!
