### ISSUE TITLE
Bug: provisional subway pattern responsive scaling

### ISSUE THREAD

**Issue by Borges-Porteous** [wet-boew/GCWeb#1715]
When scaling down the [Subway pattern working example](https://wet-boew.github.io/themes-dist/GCWeb/demos/gc-subway/gc-subway-en.html) in the inspect tool or browser, the new provisional subway pattern seems to have a bug which causes the first H1 to not appear.

Note:
- This bug does not appear to occur if you load in the small screen size
- The bug will **randomly** not occur when the screen width is shrunk (very odd that it sometimes doesn't occur...)

![Screen Shot 2020-08-17 at 1 07 44 PM](https://user-images.githubusercontent.com/22773687/90424156-a74ae200-e08b-11ea-8a61-3ac84a814b98.png)

Risk: Low

This is a low risk bug, since it won't affect users unless they are resizing their browsers. However, it would be great if we could fix it, since it will affect how people within the GC interact with the guidance and see what the pattern looks like in mobile view, when trying to simulate the mobile view on desktop computers.

Anyone know why this issue might happen in the first place?

**Comment by GormFrank** [comment]
Hi @Borges-Porteous,

I'll be working on this one. The "bug" occurs when you shrink your viewport's size too fast and doesn't when you shrink it slowly. Thank you for submitting this issue.

**Comment by delisma** [comment]
Also, as float implies the use of the block layout, it modifies the computed value of the display values, in some cases:

```
.provisional.gc-subway h1 {
	display: inline-block;
	float: left;
}
```
Specified value `inline-block` is computed as a `block` value.

source: https://developer.mozilla.org/en-US/docs/Web/CSS/float
