### ISSUE TITLE
Suggestion: bigger panel header font size

### ISSUE THREAD

**Issue by EricLavoie2** [wet-boew/GCWeb#1726]
I'm not sure if this is done on purpose, but by default the panel header is smaller than the panel body in GCWeb. I feel like it should be bigger than the body text.
![image](https://user-images.githubusercontent.com/67106245/93226756-ac11bd00-f741-11ea-9791-10382e4f2c34.png)

In the WET example for panels, the header font size is bigger than the body text:
https://webcache.googleusercontent.com/search?q=cache:oWQ9CGm7irYJ:https://wet-boew.github.io/wet-boew-styleguide/design/panels-en.html+&cd=1&hl=en&ct=clnk&gl=ca&client=firefox-b-d

**Comment by GormFrank** [comment]
You are totally right. Panel titles seem to have an hardcoded font-size value of 18px coming from Bootstrap 3, and that size never seem to be overwritten at any point making it smaller than regular text when the visual redesign occured on GCWeb a few years back, making 20px the default font-size for regular text. 
![panel-heading-vs-body](https://user-images.githubusercontent.com/4353199/93823569-07efb080-fc30-11ea-8095-09d830f54a1c.PNG)

**Comment by ctopCanada** [comment]
just test on this page /dist/unmin/demos/urlmapping/geomap-en.html
after add class 

.panel-title {
	font-size: 1.2em;
}
to this file src\components\_base.scss , the title becomes bigger than body text.
