### ISSUE TITLE
Beta theme and topic page

### ISSUE THREAD

**Issue by junsola** [wet-boew/GCWeb#1731]
Hi,

How can i implement the Beta theme and topic page? 

How can i apply custom CSS to use this beta version?

Thanks.

**Comment by GormFrank** [comment]
Hi @junsola, the beta theme and topic template isn't ready yet on GCWeb. However, it is being worked on as we speak: https://github.com/wet-boew/GCWeb/pull/1720

Once it is approved and merge, it will become a provisional template and more details (working example and/or documentation) will be available on this page: https://wet-boew.github.io/themes-dist/GCWeb/provisional-en.html
