### ISSUE TITLE
Fieldflow - apostrophe trimmed from input field value

### ISSUE THREAD

**Issue by MatthieuBonenfant-GOC** [wet-boew/GCWeb#1744]
Hi!

I want to flag this bug I found when the form input field value has a single quote in it (often used as an apostrophe). After the list is converted to a form by the WET framework, the "value" is trimmed by the single quote inside the text. We tried replacing the single quotes by double quotes inside out... no success there. The workaround for now is to replace the single quote in the text by an apostrophe character.

Thank you for looking into it.

[screenshot](https://imgur.com/a/f2kHyod)

```
<div id="services2" class="wb-frmvld" data-gc-analytics-collect="[{'value':'input','emptyField': 'N/A'}]" data-gc-analytics-formname="whoareyou">
<div id="question2" class="wb-fieldflow" data-wb-fieldflow="{
			'noForm':false,
                      	'renderas':'radio',
                      	'base': { 'live': false },
                      	'noreqlabel': true}">
<ul>
<li><a href="#1">l'enfant (single quote)</a></li>
<li><a href="#2">l&apos;enfant (apostrophe)</a></li>
</ul>
</div>
</div>
```

**Comment by duboisp** [comment]
More investigation is be needed, I think the apostrophe might just need to be escaped when creating the HTML user interface. A fix for this issue could be located somewhere around those following line:
•	https://github.com/wet-boew/GCWeb/blob/master/src/plugins/fieldflow/fieldflow.js#L816
 
•	https://github.com/wet-boew/GCWeb/blob/master/src/plugins/fieldflow/fieldflow.js#L793
•	https://github.com/wet-boew/GCWeb/blob/master/src/plugins/fieldflow/fieldflow.js#L597
•	https://github.com/wet-boew/GCWeb/blob/master/src/plugins/fieldflow/fieldflow.js#L604
 
•	https://github.com/wet-boew/GCWeb/blob/master/src/plugins/fieldflow/fieldflow.js#L446
•	https://github.com/wet-boew/GCWeb/blob/master/src/plugins/fieldflow/fieldflow.js#L226

**Comment by EricDunsworth** [comment]
#1960 should fix this :).
