### ISSUE TITLE
[OTHER] GC-Subway styling

### ISSUE THREAD

**Issue by delisma** [wet-boew/GCWeb#1749]
---
name: Other
about: Asking a question and seeking guidance
title: "GC-Subway styling"
labels: ''
assignees: '@GormFrank'

---

## Describe the purpose of this issue
I was wondering why the `_screen-min-md.scss` is duplicating the styles found in `_base.scss`?

**Comment by GormFrank** [comment]
Which styles? If you only saw a few duplicated rules, then it was probably part of the original code and will be tackled in an upcoming clean up phase.

**Comment by delisma** [comment]
> Which styles? If you only saw a few duplicated rules, then it was probably part of the original code and will be tackled in an upcoming clean up phase.

If you look in both files under the `gc-subway` conponants the styles in both files are the same.

**Comment by EricDunsworth** [comment]
FWIW these are the two files in question:
* https://github.com/wet-boew/GCWeb/blob/master/src/plugins/gc-subway/_screen-md-min.scss
* https://github.com/wet-boew/GCWeb/blob/master/src/plugins/gc-subway/_base.scss

Their styles seem distinct to me. Maybe the ``/* Double H1 */`` comment (which exists in both files) was just making it seem like a chunk of code was repeating itself?

**Comment by delisma** [comment]
After verification the empty class `.provisional` is the only one duplicating
