### ISSUE TITLE
Bug - summary/details tag does not expand when using polyfill 

### ISSUE THREAD

**Issue by aahmedgc** [wet-boew/GCWeb#1789]
## Describe the bug

I have used WET in order to build a webpage containing summary/details tags, and I have added each summary/detail tag as a row within DataTables in order to be able to filter the summary/details panes, and this implementation works natively. However, when using IE and browsers that require the polyfill, clicking on the summary/detail tag does not trigger the box to expand, however manually adding the "open" attribute to the summary/details tag reflects the correct behaviour. 

I figure this is related to using datatables and the polyfill at the same time, but not certain as to what the specific root issue is - I would appreciate some feedback.

## To Reproduce

1. Add a details and a summary tag within a table cell
2. Verify behaviour in Chrome/native (clicking the cell / summary details tag will open the summary element)
3. Attempt the same action in Internet Explorer or another browser that uses the polyfill
4. See error - summary element does not open

**Comment by jeffwylarsen** [comment]
I think you just need to trigger the polyfill after Data Tables redraws, i.e.

`$(document).on('wb-updated.wb-tables',function(){$('summary').trigger('wb-init.wb-details')});`

**Comment by aahmedgc** [comment]
> I think you just need to trigger the polyfill after Data Tables redraws, i.e.
> 
> `$(document).on('wb-updated.wb-tables',function(){$('summary').trigger('wb-init.wb-details')});`

Thank you - this was the culprit!
