### ISSUE TITLE
Canada.ca theme: left navigation

### ISSUE THREAD

**Issue by laurencechavet** [wet-boew/GCWeb#1833]
HI

I am trying to find the example page with a left navigation. I am pretty sure it was there before but I have no luck https://wet-boew.github.io/GCWeb/home.html, as we used the example code to replicate our page

![left_nav](https://user-images.githubusercontent.com/65306416/120537589-76863000-c3b3-11eb-8512-18bf0f1fa671.png)

**Comment by RobJohnston** [comment]
Something like this?  https://wet-boew.github.io/themes-dist/theme-gcwu-fegc/content-secmenu-en.html

If so, I always start from the "Working examples":  https://wet-boew.github.io/wet-boew/demos/index-en.html

**Comment by laurencechavet** [comment]
Hi
yes exactly like that. I started the same place than you "working examples", then "canada theme" and then I could not find it. I looke all the template of the canada theme, in working example I looked for navigation, left, menu (only the top menu). But nothing. I am sure it existed before
Do you know where I can find the example, or if this was removed from the examples. I think in the templates it was called secondary menu.
Thanks

**Comment by RobJohnston** [comment]
I don't know any more, but I would suspect that it would be the same, or at least very similar, markup in the other theme.

**Comment by laurencechavet** [comment]
You know I did not think to look at other theme, silly me. In the base theme I found it https://wet-boew.github.io/themes-dist/theme-base/content-secmenu-en.html
Sorry I wasted your time. Thank you for the hint :)
