### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by jlcharette** [wet-boew/GCWeb#1994]
![image](https://user-images.githubusercontent.com/44408591/178281380-215be08d-5abd-4af0-acac-47e50c13e9c3.png)

The links (header & footer) in this screenshot are dead.

Link: https://wet-boew.github.io/GCWeb/docs/implementing.html

**Comment by Ricokola** [comment]
Links have been fixed in release [v11.4.0](https://github.com/wet-boew/GCWeb/releases/tag/v11.4.0):
- https://wet-boew.github.io/GCWeb/docs/implementing-en.html
- https://wet-boew.github.io/GCWeb/docs/implementing-fr.html

 Therefore, I suggest closing this issue...
