### ISSUE TITLE
Bug - h1 style looks "wrong" for Safari iOS 14

### ISSUE THREAD

**Issue by muling** [wet-boew/GCWeb#2396]
## Describe the bug

Extra red border appears in the h1 title in Safari

## To Reproduce

Steps to reproduce the behaviour:
1. Go to any canada.ca page with the latest GCWeb template
2. view h1

## Example

https://www.canada.ca/en/services/jobs.html

## Current behaviour

see extra red borders in screenshot

## Expected behaviour

should look like this
![image](https://github.com/user-attachments/assets/6721e86f-78f4-4b88-be04-bd78d5b438d1)

## Screenshots and/or logs

![image](https://github.com/user-attachments/assets/a0eb42ed-984d-48ff-b4bf-9d3c477d0df8)

## Desktop (please complete the following information):

 - OS: iOS
 - Browser:Safari
 - Version: 14 (or below)
Ok on v15+

## Smartphone (please complete the following information):

 - Browser: [e.g. stock browser, safari]
 - Version: [e.g. 22]

## Additional context

You can add any other context about the problem here.

**Comment by EricDunsworth** [comment]
Looks like https://github.com/wet-boew/GCWeb/pull/2169#discussion_r1222125775 is afflicted by a ``border-image`` rendering bug in several older browser rendering engines (WebKit, Blink and EdgeHTML).

Check out note 1 in [Can I use's CSS3 Border images page](https://caniuse.com/border-image)'s for more info. In a nutshell, using the ``border-image`` property apparently causes affected browsers to silently-set ``border-style: solid;``. I was able to replicate the buggy screenshot by adding that property to the H1 in Firefox's DOM inspector.

**Comment by EricDunsworth** [comment]
@muling I tried prototyping potential fixes in [this JSBin page](https://jsbin.com/sifedejice). Would you happen to be able to take a screenshot of it in iOS Safari 14 if possible? "H1 thickline" represents the pre-existing CSS, whereas test1-4 represent potential fixes.

@delisma @Garneauma Would you be on board if I were to send a PR to fix this (given that it only impacts older browsers)? I feel kind of responsible since I suggested the selector that caused it 😅.

Can I Use... claims that the bug wasn't fixed in Safari until v15.4 (released in March 2022). I think that'd technically be beyond the scope of GCWeb's supported browsers, but is still relatively recent...

**Comment by muling** [comment]
Sure. I can send a request with a screenshot to principal publisher.

**Comment by muling** [comment]
> @muling I tried prototyping potential fixes in [this JSBin page](https://jsbin.com/sifedejice). Would you happen to be able to take a screenshot of it in iOS Safari 14 if possible? "H1 thickline" represents the pre-existing CSS, whereas test1-4 represent potential fixes.
> 
> @delisma @Garneauma Would you be on board if I were to send a PR to fix this (given that it only impacts older browsers)? I feel kind of responsible since I suggested the selector that caused it 😅.
> 
> Can I Use... claims that the bug wasn't fixed in Safari until v15.4 (released in March 2022). I think that'd technically go beyond the scope of GCWeb's supported browsers, but is still relatively recent...

You cannot see the screenshot in the original ticket?

**Comment by EricDunsworth** [comment]
> You cannot see the screenshot in the original ticket?

I can see your opening post's screenshots, but I don't have Safari at my disposal :(. So I'm unable to tell whether my fix attempts in [this JSBin page](https://jsbin.com/sifedejice) will fix it for sure. So someone will need to verify in Safari v15.3 or lower.

**Comment by muling** [comment]
oh sorry for the misunderstanding. here is the screenshot.

![image](https://github.com/user-attachments/assets/62771055-da29-4499-ac9f-da191fa02cdd)

**Comment by EricDunsworth** [comment]
@muling Thanks :)! I'll try sending a PR using test4's approach later today.

**Comment by duboisp** [comment]
I found out that the CSS Gradient is not supported by Safari older than 15.4. - https://caniuse.com/css-gradients

Which means the CSS "linear-gradient" use in the `border-image` is not supported.

@muling Thanks for submitting the request to Principal Publisher, we will follow up on your request over there.

**Comment by EricDunsworth** [comment]
@duboisp Although the screenshot in https://github.com/wet-boew/GCWeb/issues/2396#issuecomment-2284508923 shows the gradient working in all 5 examples and test4 looks perfect. So that gradient bug doesn't actually affect the thickline style in practice.

**Comment by muling** [comment]
> Sure. I can send a request with a screenshot to principal publisher.

I've been getting errors trying to submit the request...

![image](https://github.com/user-attachments/assets/b4ef503d-371b-40d8-9e9b-62b6b3f09545)

**Comment by EricDunsworth** [comment]
Just sent #2415.

@duboisp Feel free to do whatever you want with it :).
