### ISSUE TITLE
Multimedia Player - Firefox and Opera... so far

### ISSUE THREAD

**Issue by MRicher** [wet-boew/GCWeb#487]
When you forward, pause, reverse and play. The loading icon stays put on the video while it's playing.  Couldn't replicate in Chrome since the reverse button not working.

**Comment by Bgolden67** [comment]
I was about to open an issue about this, we are still seeing this happen however I did a test using the example video page and this occurs on my work computer, but when i test the same page at home on my personal connection, it didn't seem to be a problem. 
Has anyone else tested this internally vs externally? and is there any progress on a fix or is it out of a WET issue scope?
