### ISSUE TITLE
Canada.ca carousel - links in text overlay

### ISSUE THREAD

**Issue by pcwsmith** [wet-boew/GCWeb#673]
Tested in a couple browsers, and it looks like the default state for links in the text overlay is non-underlined, with the underlining appearing on hover.

Thinking that to be consistent with link styling in the rest of content area, the underlines should appear in the default state.

**Comment by hsrudnicki** [comment]
@masterbee, based on http://ux.stackexchange.com/questions/7064/when-should-hyperlinks-be-underlined, also see updated wet-boew/wet-boew-styleguide#25, @thomasgohard seems be right, unless other strong argument, can we close the issue?

**Comment by hsrudnicki** [comment]
@pcwsmith, as originator of the issue, are you ready to close it?

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/wet-boew/issues/5574 - WET documentation pages that need to be completed

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/wet-boew/issues/6550 - SCSS variables: Overlay Plugin questions

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/wet-boew/issues/6551 - SCSS variables: Inventory

**Comment by LaurentGoderre** [comment]
The last two issues are not related to this.

**Comment by hsrudnicki** [comment]
No problem, above all I relay on your experience, just by occasion, I assumed that this issue is a styling dilemma in regards to links' text within overlay text, and maybe as one of more possibilities, Sass lets use some features like variables in styling including this issue case

**Comment by hsrudnicki** [comment]
Maybe partially helpful, the following styling issue also referring to the link's underline, before settling on a decision/solution, into consideration is: https://github.com/wet-boew/wet-boew/issues/4515

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue can be closed as resolved/fixed or otherwise? If otherwise, label this issue as "Going Stale"? Thank you

**Comment by hsrudnicki** [comment]
Is this still an issue, referenced with/to the other issue(s)? Either way, please update the status of this issue, whether this issue can be closed as resolved/fixed or otherwise, thank you
