### ISSUE TITLE
404 page concerns

### ISSUE THREAD

**Issue by bsouster** [wet-boew/GCWeb#700]
A Web Advisor at CIC made a few good points about the 404 page.

1. The search boxes do not contrast well against the background. They're really hard to see. I hadn't even noticed them until she pointed it out.

2. The semi-colons at the end of the third bullets look odd. If it's the end of the list; they should be periods. (en + fr)

**Comment by hsrudnicki** [comment]
@bsouster did you implemented the two points found, and do you need more supporting details to close the issue? 
Additional Note, based on http://www.404errorpages.com, the World Wide Web Consortium (W3C) states that 404 Not Found should be used in cases where the server fails to find the requested location and is unsure of its status. Whenever a page has been permanently removed, the status code used must be 410.

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/wet-boew/issues/1191 - 404 Page

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/wet-boew/issues/6819 - v4.0.14 dist 404 page missing <header> section
