### ISSUE TITLE
Canada logo in footer does not fit properly in viewport on mobile

### ISSUE THREAD

**Issue by andrewleith** [wet-boew/GCWeb#871]
This causes horizontal scrolling.

![image](https://cloud.githubusercontent.com/assets/823749/5417012/2f0c5734-8203-11e4-9dec-ae3023b999b8.png)

After scrolling to the right:
![image](https://cloud.githubusercontent.com/assets/823749/5417016/358f4a6c-8203-11e4-9b55-4386c611b854.png)

**Comment by andrewleith** [comment]
The issue is that the footer is divided into two col-6's in mobile, but the logo has a fixed width of 178px which exceeds its 50% allowance on some devices (any device with a screen width smaller than around 400px).

One fix would simply to set a max-width on the object tag, i.e., `max-width: 100%`. This would just squish the image on skinny phones.

**Comment by LaurentGoderre** [comment]
It probably be safer to apply this safe to that view only. Are you able to open a PR for this?

**Comment by andrewleith** [comment]
We aren't able to actually get WET working here at stats. Configuring the proxy is a bit of a challenge.  There was some dependency via NPM (openlayers maybe?) that you couldn't configure to use the proxy.

So, from here, I don't think I can get a working version of WET.

We had to build it from home...

**Comment by LaurentGoderre** [comment]
@andrewleith perhaps I could help you with that, I was able to fix it for Service Canada's proxy

/cc @EricDunsworth @shawnthompson

**Comment by EricDunsworth** [comment]
@andrewleith If you're not already aware of it, check out this page in WET's documentation: http://wet-boew.github.io/wet-boew/docs/proxy-en.html.

Btw in my department we don't need to include the ``:PASSWORD`` part in proxy URLs. In fact, including passwords prevents it from working for us. So if you have trouble you might want to try with and without that part.

As for the "Setting the proxy for other tasks" section, if you're using Windows, you can avoid the need to setup RC files or use Git Bash if you setup account/system environment variables for HTTP_PROXY and HTTPS_PROXY.
