### ISSUE TITLE
Problem with Government of Canada activities and initiatives when JS is disabled

### ISSUE THREAD

**Issue by pjackson28** [wet-boew/GCWeb#883]
When JS is disabled, only the "Government of Canada activities and initiatives" heading remains. In that case, either put activities and initiatives in the section or hide the heading.

**Comment by LaurentGoderre** [comment]
Are the priority still using the central soultion?

**Comment by masterbee** [comment]
@pjackson28 did you experience this in the template or on Canada.ca? There is some experimentation happening with JS approach to the priorities but this should not be reflected in the template.

**Comment by pjackson28** [comment]
It's just Canada.ca as the templates at least have placeholder content.

**Comment by MRicher** [comment]
@pjackson28, @LaurentGoderre and @masterbee. just tested by adding this at the footer for a temporary solution.
```javascript
if (localStorage.getItem("wbdisable") == "true" || $.QueryString("wbdisable") == "true") 
{ 
$('aside.gc-nttvs').hide();
}
```
maybe we can add this in the theme.js?

**Comment by LaurentGoderre** [comment]
Shouldn't this be handled in the solution instead of using a hack?

**Comment by MRicher** [comment]
@LaurentGoderre I agree, in my view the whole aside section should be push by the central pull.

**Comment by LaurentGoderre** [comment]
@masterbee would you be ready to apply this change?

**Comment by masterbee** [comment]
@LaurentGoderre we have already implemented this in the solution so there a proper no JS fallback in the provided code. Closing since addressed
