### ISSUE TITLE
Should Remove "Regulations under this Act" Paragraph from Regulations Template

### ISSUE THREAD

**Issue by jdmlouis** [wet-boew/GCWeb#884]
* Originally posted as https://github.com/wet-boew/wet-boew/issues/6466

As Regulations will not have Regulations attached to them (only Acts have Regulations attached to them), the portion entitled "Regulations under this Act" should be removed as redundant from the Regulations Template.

Quick link for review: http://wet-boew.github.io/themes-dist/GCWeb/regulations-en.html and http://wet-boew.github.io/themes-dist/GCWeb/regulations-fr.html

![regulations](https://cloud.githubusercontent.com/assets/675897/5863070/ca316e78-a244-11e4-9781-5e964859d89f.PNG)

**Comment by MRicher** [comment]
Done with merge pull request #887
