### ISSUE TITLE
Glyph icons are not printing properly in Canada.ca theme template only

### ISSUE THREAD

**Issue by ehcee** [wet-boew/GCWeb#888]
Hi,

I've noticed a bug in the Canada.ca templates when using Glyph icons where they do not appear when you print the page to paper, ie

<span class=”glyphicon glyphicon-arrow-up”></span>

In Canada.ca template only (works in the other ones I tested it on), when using Glyphicons they appear properly in the browser, however when I goto "Print Preview" (ie in firefox of chrome), none of the glyph icons appear in the print version, see screen shot below:

![glyph-icon2](https://cloud.githubusercontent.com/assets/5295103/6007777/d474002c-aaea-11e4-8a04-df178eebef29.jpg)

Note I also tested adding the glyph icons to the base and GCWU templates and they work fine in print mode

![glyph-icon1](https://cloud.githubusercontent.com/assets/5295103/6007796/f19026b8-aaea-11e4-9c6b-8d14f13fa83c.jpg)
, see screenshot

I believe the issue is unique to canada.ca template.

If there is a resolution before the next release, could i also get the code snippet to implement in our existing templates.

thanks

**Comment by LaurentGoderre** [comment]
Glyphicons are working in your screenshot (Look at the breadcrumb arrow glyphicons) so it probably is an issue in how you include those custom glyphicons

**Comment by ehcee** [comment]
The problem only occurs when using the <span>'s to implement them, ie:
<span class=”glyphicon glyphicon-arrow-up”></span>

As found in the instructions here:
http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html#coding

The breadcrumbs don't have the <span class="glypicon......"> implementation but have them embedded in the CSS for the breaddrumbs

You'll note the WET Style guide that uses one of the base templates works fine when you "Print Preview" however, if you embed those <span class="glyphicon...."> in the canada.ca templates they do not show up.

**Comment by ehcee** [comment]
Sorry github filters out my code examples from above:

The problem only occurs when using the SPAN's to implement them, ie:

As found in the instructions here:
http://wet-boew.github.io/wet-boew-styleguide/v4/design/icons-en.html#coding

The breadcrumbs don't have the SPAN implementation but have them embedded in the CSS for the breaddrumbs

You'll note the WET Style guide that uses one of the base templates works fine when you "Print Preview" however, if you embed those SPAN GLYPHICON'S in the canada.ca templates they do not show up when you "Print Preview"

**Comment by LaurentGoderre** [comment]
@ehcee use the ` aroind code to make sure it displays correctly

**Comment by ehcee** [comment]
Any `<span class="glyphicon ..."></span>` I put in the canada.ca template, shows in browser but does not print (ie check print preview), this was tested in Firefox and chrome. It does work fine in the WET base template, and the blue gcwu template.

Any css implementation where it inserts glyph icons ie breadcrumbs works/prints fine... Just the span implementation doesn't work in Canada.ca template.

**Comment by LaurentGoderre** [comment]
Can you please close and reopen on the GCWeb repo since it only applies to that theme

**Comment by LaurentGoderre** [comment]
It's this line that causes the issue https://github.com/wet-boew/GCWeb/blob/master/src/views/_print.scss#L15 

@pjackson28 do you remember why you added that line?

**Comment by pjackson28** [comment]
@LaurentGoderre I didn't. I just changed the existing display none into an extend.

**Comment by LaurentGoderre** [comment]
Oh, sorry, any idea why that was done in the first place?

**Comment by pjackson28** [comment]
No idea unfortunately.

**Comment by LaurentGoderre** [comment]
Anything against removing that part?
