### ISSUE TITLE
.table-striped is not consistently changing table header background colours

### ISSUE THREAD

**Issue by ehcee** [wet-boew/GCWeb#889]
I noticed an issue when applying the .table-striped class to tables that have headers outside of <thead> (ie headers in the left column) whether there is a <tbody> or not, see basic table screenshot below:

![z-tables-no](https://cloud.githubusercontent.com/assets/5295103/6008416/50f3fc8e-aaef-11e4-972f-7c0b94a26515.jpg)

When I apply the class .table-striped to the table, ie
<table class="table table-striped">

The background colours for one of the alternating rows overrides the table header <th> background colour which is a darker grey, see screen shot below:

![z-tables-with](https://cloud.githubusercontent.com/assets/5295103/6008423/5c2f6d54-aaef-11e4-9622-96222cb7e23b.jpg)

Could this be fixed to either:
(1) have both even/odd alternating rows not override the table header <th> so that it remains dark grey
or
(2) have both alternating even/odd rows override the table header background colour with there alternating colours (instead of currently each alternating row overriding it)

**Comment by ehcee** [comment]
I guess have my description got embedded in the image embed feature when making a github issue, here is the description portion:

When I apply the class .table-striped to the table, ie

The background colours for one of the alternating rows overrides the table header background colour which is a darker grey, see screen shot below:

Could this be fixed to either:
(1) have both even/odd alternating rows not override the table header so that it remains dark grey
or
(2) have both alternating even/odd rows override the table header background colour with there alternating colours (instead of currently each alternating row overriding it)

**Comment by LaurentGoderre** [comment]
Can you add a picture of the result you want to achieve?

**Comment by ehcee** [comment]
No prob, currently we have this:

![z-tables-with](https://cloud.githubusercontent.com/assets/5295103/6008986/c4a759e2-aaf3-11e4-8a81-c3c86992b5c6.jpg)

I think we can agree it's not the ideal way, Here are my 2 suggestions below:

Keep Table Header backgrounds:

![ztable4](https://cloud.githubusercontent.com/assets/5295103/6009000/dfebd03e-aaf3-11e4-9ea7-63de8f2d3d60.jpg)

Remove table header backgrounds for both rows:

![ztable3](https://cloud.githubusercontent.com/assets/5295103/6009002/eaa11818-aaf3-11e4-9dc7-ea26afe29424.jpg)

As for my preferance, i believe this change will applied to the templates and rolled out to all departments to implement. I don't have a preferance but am presuming since it has to do with the presentation of content that it would be the central publisher or Treasury board that would want to decide how this layout looks.

cheers

**Comment by shawnthompson** [comment]
This should be fixed with the development build.

Fixed in:
https://github.com/wet-boew/GCWeb/commit/9d8fc77de81e76cf96c0ed3b2b7c38fc707fb984

**Comment by LaurentGoderre** [comment]
Actually this fix was included in v4.0.10. Can you try updating to that version

**Comment by hsrudnicki** [comment]
@ehcee @LaurentGoderre @shawnthompson: the issue when applying the .table-striped class to tables had been explained/implemented, so can we close this issue?
FYI to speed up your decision: In past there had been related issue(s) raised that are closed: #329, https://github.com/twbs/bootstrap/issues/11728, also see current  http://getbootstrap.com/css/#tables-striped

**Comment by ehcee** [comment]
Works when i test it, no issues on my part if you close it.

**Comment by hsrudnicki** [comment]
@ehcee @LaurentGoderre @shawnthompson: if it works, no further question(s), then the issue can be closed by originator or one of you
