### ISSUE TITLE
Footnote overlap

### ISSUE THREAD

**Issue by EricLavoie88** [wet-boew/GCWeb#893]
When using the "Print Preview" options in IE and FF, the links in brackets following the footnotes at the bottom of the page overlap the text that follows.

**Comment by pjackson28** [comment]
Could you please file this in wet-boew/wet-boew? This seems to be an issue with WET core rather than being specific to the Canada.ca theme.

Could you please also attach a screen shot to the new issue as well just so the problem is clear?

@EricDunsworth fyi

**Comment by pjackson28** [comment]
Replaced by wet-boew/wet-boew#6500
