### ISSUE TITLE
GoC initiatives and activities links using super wide linked area in small view

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/GCWeb#894]
The title pretty much says it all. All versions of GCWeb seem to be affected.

The blue highlighting in the following screenshot represents the link's "clickable" area.

**Screenshot:**
![goc-activities-initiatives_linked-area](https://cloud.githubusercontent.com/assets/1907279/6129124/e1d0adc2-b109-11e4-9a13-1e689cb7bd85.png)

**Example link:**
http://wet-boew.github.io/themes-dist/GCWeb/index-en.html

Was this intentionally done to make it easier for touch screen users to click the links in question? Seems kind of excessive IMO.

**Comment by LaurentGoderre** [comment]
Does it cause any issue though?

**Comment by EricDunsworth** [comment]
IMO it's a usability issue. If a user perceives a large empty space beside a link and clicks/touches the area for another reason, they wouldn't expect to be lead out to a different page.

I also sometimes find myself erroneously clicking it while in mobile view (in a desktop browser).

**Comment by LaurentGoderre** [comment]
Hmm, guess so...

**Comment by EricDunsworth** [comment]
I've come up with a WIP fix but it only works properly with HTML changes (adding a hollow div between the heading and subsequent image).

Really wished Firefox supported the ``line-break`` CSS3 property... :(.

**Comment by LaurentGoderre** [comment]
I would prefer trying to find a fix that does not involve a markup change because this would have big implications

**Comment by EricDunsworth** [comment]
Ditto. I'll see whether I can come up with something that doesn't necessitate HTML changes.
