### ISSUE TITLE
Add Bootlint to the build

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/GCWeb#903]
Bootlint is a very nice utility that ensures that we are using Bootstrap in the way it was intended to

**Comment by hsrudnicki** [comment]
@LaurentGoderre: Shall we keep the issue still open or closed if Bootlint has been implemented?

**Comment by LaurentGoderre** [comment]
Bootlint has not been implemented so it should remain open

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/wet-boew/issues/6517 - grunt-bootlint version is outdated
https://github.com/wet-boew/wet-boew/pull/6524 - WIP: Updated Bootlint to the latest version

**Comment by masterbee** [comment]
@LaurentGoderre - since I know that there is some re-working of the themes and WET going on, would it be safe to say this would be handled better upstream in WET as a build requirement or do you see the themes still having to bootlint on build as well.

**Comment by LaurentGoderre** [comment]
Each theme should have it as well
