### ISSUE TITLE
Standardize the "date modified", "feedback" and "share" elements across all templates

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#925]
Most of the templates use these three consistently, but there are a number of pages that don't. I'm guessing we should probably standardize these across all templates across the board.

One of these days I suppose we should also get around to documenting these in the spec, too :)

**Comment by LaurentGoderre** [comment]
Can you point example where it's not...there are standard include files we use to keep it consistent so if there are area not using those they should be changed.

**Comment by DK-TBS** [comment]
Hey, sure thing LG.  Just took a fresh look through, here's a list of the pages that might need attention:

http://wet-boew.github.io/themes-dist/GCWeb/content-en.html

http://wet-boew.github.io/themes-dist/GCWeb/feedback-en.html

http://wet-boew.github.io/themes-dist/GCWeb/widgets-en.html

http://wet-boew.github.io/themes-dist/GCWeb/blog-en.html

http://wet-boew.github.io/themes-dist/GCWeb/partners/index-en.html

http://wet-boew.github.io/themes-dist/GCWeb/content-fr.html

http://wet-boew.github.io/themes-dist/GCWeb/feedback-fr.html

http://wet-boew.github.io/themes-dist/GCWeb/widgets-fr.html

http://wet-boew.github.io/themes-dist/GCWeb/blog-fr.html

http://wet-boew.github.io/themes-dist/GCWeb/partners/index-fr.html

**Comment by shawnthompson** [comment]
It's using the front matter to turn it on and off, but if it always has to be on can we remove that?

**Comment by LaurentGoderre** [comment]
@shawnthompson leave the option there even if they're always one...it's better to have more control than not enough

**Comment by shawnthompson** [comment]
@DK-TBS the blog doesn't have a share this page because of it's at the beginning of the page.
http://www.canada.ca/blog/

**Comment by shawnthompson** [comment]
New pull request without the feedback deletion... yet

**Comment by shawnthompson** [comment]
https://github.com/wet-boew/GCWeb/pull/936
