### ISSUE TITLE
Tweak to names of links to adv. serv initiation page on the index page

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#926]
Let's change “Advance service initiation pages” to “Advance**d** service initation pages”

**Comment by shawnthompson** [comment]
Advanced service initation pages
or
Advanced service initiation pages

**Comment by DK-TBS** [comment]
Ach!  I included a typo when asking for a typo fix.  Yes, "Advanced service initiation pages" for sure  :)

**Comment by shawnthompson** [comment]
PR in
https://github.com/wet-boew/GCWeb/pull/928
