### ISSUE TITLE
Add 3 new doormats to the home page (the live site and the template)

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#927]
Latest version of the spec requires 3 new doormats added below the ones already there. They'll be for 3 GC-Wide audiences: Seniors, Aboriginals, Veterans.

Not sure if we're going to keep the homepage in the demo template collection here... departments certainly won't ever need to have access to it.  Up to you guys.  But if we do keep the template we should add the 3 new doormats there, as well. 

I haven't seen any doormat blurbs for these, though.  Is it someone at servicecan who would be writing and publishing those to the live site?

**Comment by shawnthompson** [comment]
Here's what it looks like on page 54 of the IA specs

![capture](https://cloud.githubusercontent.com/assets/2575266/6395273/441c4eb2-bda5-11e4-945b-e5179ed9a56d.JPG)

**Comment by quicklunarcop** [comment]
Dave, I would ask Gil to see when TBS wants to have those links added. To date, only the Seniors content is developed.

The descriptions should come from the people managing the Audience pages, not from PP.

**Comment by DK-TBS** [comment]
Ah!  Okay, now I understand - sorry about that guys.  

I just asked Gil about the status of the audience pages, and he said they're definitely not ready yet - so I'm closing this issue down, with my apologies  :)
