### ISSUE TITLE
Tweaks to simple service initiation landing page

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#929]
http://wet-boew.github.io/themes-dist/GCWeb/service-en.html

http://wet-boew.github.io/themes-dist/GCWeb/service-fr.html

* We should remove the square brackets around the headings of the sidebar items, so that authors aren’t tempted to make up new headings haphazardly. 

* Same for the “other ways to apply” heading, we should remove the brackets to help reinforce the idea that the element is mandatory

* The rest of the main body content (the background info) is discretionary, so no worries there, that part is good as it is

* Nitpicky thing:  let’s change the “Related services and info” sidebar heading to “Related services and information” just to be more consistent with the spec

* We’re going to need a third sidebar element in there called “Related program”.  The spec doc is missing some details around this part, we’ll fix that on our end.  (Sorry, I'd attach a screenshot of the missing sidebar, but IE9 won't let me attach images to issues.  It looks just like the other sidebar elements, but titled "Related program" with a single bullet for "[Program name]")

**Comment by hsrudnicki** [comment]
@DK-TBS: Do you need more details/inputs to solve and close the issue?
Based on the above, there is no any discussion following, it's left to you, I think that you should implement the design changes into the project and/or then you should address made changes to others involved in the project.

**Comment by DK-TBS** [comment]
Hey there @hsrudnicki!  Sorry for the slow response - my casual ended so I wasn't in the office for a while.  I'm back now, and should be around until at least October, hopefully longer.  Trying to get caught up here  :)

Anyway, I'm not actually equipped to make changes to the project myself, this was intended to be more of a task reminder to the guys at SC, just to make some tweaks to get the template to match the spec.  I'm going to close the issue for now though, because it sounds as though there will be some other changes coming down the pipe for the simple and advanced service initiation templates.  We'll revisit it all later on.
