### ISSUE TITLE
Tweaks to advanced service initiation page

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#930]
http://wet-boew.github.io/themes-dist/GCWeb/servicecomplexe/index-en.html

http://wet-boew.github.io/themes-dist/GCWeb/servicecomplexe/index-fr.html

* The page title H1 should show two parts:  the service name, and the currently selected section/sub-page.  So in this case, it should read “[Service name] – [Overview]”

* There should also be a numbered heading just underneath the submenu, to further reinforce the user’s current location.  So in this case it should read “1. [Overview]”, just before the first paragraph of main page content.

* We should remove the square brackets around the headings of the sidebar items, so that authors aren’t tempted to make up new headings haphazardly.

* Nitpicky thing:  let’s change the “Related services and info” sidebar heading to “Related services and information” just to be more consistent with the spec

* We’re going to need a third sidebar element in there called “Related program”.

* The “[Eligibility]” text in the “next” link should be marked with a number reflecting that page’s order in the sequence of sub-pages.  So in this case it should be “2. [Eligibility]”

**Comment by hsrudnicki** [comment]
@DK-TBS : is the issue ready to be closed?
Here are similar issues in regards to making little tweaks in standard form pages of different wet-boew projects to be used in the GCWeb project:
https://github.com/wet-boew/GCWeb/issues/929 to simple service initiation landing page
https://github.com/wet-boew/GCWeb/issues/922 for Feedback form page

**Comment by shawnthompson** [comment]
I assigned it to myself. Please ignore the reference.

**Comment by hsrudnicki** [comment]
@shawnthompson @DK-TBS : So who is in charge of this issue, are you closer to closing it?

**Comment by pcwsmith** [comment]
events have overtaken this one I think - see issue #971

**Comment by shawnthompson** [comment]
How did I not see that other issue... I guess we can close this, makes my job easier (for now)

**Comment by neoinsight** [comment]
Whoa - @shawnthompson @DK-TBS, issue #971 is about a future template - we have to test it first - and the test should be built upon the most current version of the template. All of the bullets in the item above still need to be done.
