### ISSUE TITLE
Tweaks to Acts page

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#932]
http://wet-boew.github.io/themes-dist/GCWeb/act-en.html

* The spec allows for a secondary bit of smaller text in the H1 title, where the date and version numbers may be included if desired, ie. `[Act name] ([NN-XX])`

* “Responsible Ministers” has been dropped to singular.  So we should remove the “s” at the end and remove the second link “Minister of [Ministry B]”

* “Related Institutions” should use a lowerase “i” on institutions.  “Minister” and “Act” are the only ones that should be capitalized

* Seeing an unnecessary horizontal scrollbar in the content area of the “Legislative change” tab (in IE9)

* Under the “Legislative change” tab:  typo in “Related forward regula**r**tory plans” heading

**Comment by shawnthompson** [comment]
PR in
