### ISSUE TITLE
Tweaks to regulations page

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#933]
http://wet-boew.github.io/themes-dist/GCWeb/regulations-en.html

* The spec allows for a secondary bit of smaller text in the H1 title, where the date and version numbers may be included if desired, ie. `[Regulation name] ([NN-XX])`

* Remove the “Responsible Ministers” block entirely

* “Related Institutions” should use a lowerase “i” on institutions.  Only “Act”s should be capitalized

* “Related regulations” should be added underneath "Related Acts", so we'll have both.  (I can't attach a screenshot, refer to the spec)

* Seeing an unnecessary horizontal scrollbar in the content area of the “Legislative change” tab (in IE9)

* Under the “Legislative change” tab:  typo in “Related forward regula**r**tory plans” heading

**Comment by shawnthompson** [comment]
@LaurentGoderre, How can the first one be accomplished using the front matter?

    The spec allows for a secondary bit of smaller text in the H1 title, where the date and version numbers may be included if desired, ie. [Regulation name] ([NN-XX])

Output would be `<h1>[Regulation name] <small>([NN-XX])</small></h1>`

**Comment by shawnthompson** [comment]
@DK-TBS or @quicklunarcop can I get a French translation for the following, please:
```html
<h2>Regulations under this Acts</h2>
<ul class="list-inline">
	<li><a href="#">[Regulation name A]</a>,</li>
	<li><a href="#">[Regulation name B]</a>,</li>
	<li><a href="#">[Regulation name C]</a></li>
</ul>
```

**Comment by DK-TBS** [comment]
I'll defer to Mr QLC.  We're not all that good at translation here on our end  :)

**Comment by shawnthompson** [comment]
I'll just use the content from this page...

http://wet-boew.github.io/themes-dist/GCWeb/act-fr.html

**Comment by shawnthompson** [comment]
PR in
