### ISSUE TITLE
Translations out of date on Organizational profile

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#937]
I guess Luc-Rock and Melanie never got a chance to review the Organizational profile, did they?

I know we're supposed to be all done and locked down on the OP templates, but I'm sure they'd want some of the same french translation changes they asked for on the IP to also be applied to the OP:

* The translation for the audience sidebar "Autres renseignements pour les"

*  Translation for the "all related laws..." link:  "Tous les règlements et lois connexes"

* "Information organisationnelle" should be "Renseignements sur l’organisation"

**Comment by shawnthompson** [comment]
Thoughts @quicklunarcop? If you agree I'll make the change.

**Comment by shawnthompson** [comment]
I changed the first translation

     The translation for the audience sidebar "Autres renseignements pour les"

In #939, I'll make the other changes once merged

**Comment by shawnthompson** [comment]
PR in

**Comment by quicklunarcop** [comment]
@shawnthompson Yes, changes that were made on IP should be done on OP as well. Thanks.

**Comment by shawnthompson** [comment]
Thanks @quicklunarcop. Changes have been made.
