### ISSUE TITLE
Small screen search/menu icon - blue rectangle perceived as clickable

### ISSUE THREAD

**Issue by pcwsmith** [wet-boew/GCWeb#940]
Was just going over the usability testing reports from the last round and I noticed an issue I neglected to bring forward.

On small screens when the search/menu icon drops below the GC signature, the blue rectangle extends across the screen width. In testing sessions with mobile device participants, some of them tried to click the blue area to the left of the search icon. Resulted in confusion since this portion of the rectangle is not clickable. It should be, since it is perceived as such.

Here's a videoclip: http://www.screencast.com/t/mbZMnxrDGX

cc @neoinsight

**Comment by LaurentGoderre** [comment]
100% agree!

**Comment by LaurentGoderre** [comment]
@shawnthompson please open a PR for this

**Comment by neoinsight** [comment]
Glad to see this, because I saw it again with mobile participants on Saturday.

**Comment by shawnthompson** [comment]
I'm on it!

**Comment by shawnthompson** [comment]
I made all the blue clickable in both small and xsmall screen sizes.

![screen shot 2015-03-19 at 1 31 12 pm](https://cloud.githubusercontent.com/assets/2575266/6736622/5b8a2afe-ce3c-11e4-8e8b-38fbc3801d0e.png)
![screen shot 2015-03-19 at 1 31 27 pm](https://cloud.githubusercontent.com/assets/2575266/6736623/5b8d2786-ce3c-11e4-8356-132295e85b04.png)

Is that what you wanted?

**Comment by neoinsight** [comment]
Yup! Thanks.

**Comment by shawnthompson** [comment]
PR coming right at you... soon
