### ISSUE TITLE
Little glitch in new homepage carousel

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#941]
http://wet-boew.github.io/themes-dist/GCWeb/home-en.html

Not sure if this is only a problem in IE9 (I've only got one browser here), but - when I leave the carousel running, and I scroll down to the bottom of the homepage, the transition to the next slide sets the focus back up to the thumbnail area. As a result, I am automatically scrolled back up to a slide thumbnail, every time the carousel advances...

**Comment by LaurentGoderre** [comment]
The issue happens on every browser and have been reported to WET core

https://github.com/wet-boew/wet-boew/issues/6533

**Comment by pjackson28** [comment]
Will be fixed by https://github.com/wet-boew/wet-boew/pull/6573
