### ISSUE TITLE
Links for latest news not working on institution template page (grid system medium)

### ISSUE THREAD

**Issue by Joberrr** [wet-boew/GCWeb#947]
Concerning institution-en.html line 165.
Links for the 'Latest' news items with photos will not work when the browser window size is medium (col-md-6). The links will work without issue when the browser window is large (col-lg-4) or when it is small (single column).

Example page (be sure to resize browser to medium layout size):
http://www.canada.ca/en/gov/dept/transport.html

**Comment by shawnthompson** [comment]
You need to add a `<div class="clearfix visible-md"></div>`. I'll add it to the files on here

**Comment by hsrudnicki** [comment]
@Joberrr @shawnthompson : Can we close this issue?
It's explained by @shawnthompson and additionally see the fix on http://getbootstrap.com/css/#grid-responsive-resets

**Comment by Joberrr** [comment]
Yes, that fixed it for me.
Thanks!
