### ISSUE TITLE
4.0.11 templates - print margin issue in Firefox

### ISSUE THREAD

**Issue by ehcee** [wet-boew/GCWeb#948]
Hi,

We've updated our site templates to version 4.0.11 and noticed an issue when printing web content in Firefox. In Firefox we have the option to scale the content to fit on the page better however as you scale the content down it adds more and more margin padding on the sides when one prints:

ie 100% fits standard margins
ie 50% which makes text size smaller, but adds more margin padding to sides so the content getting printed only takes up 50% of the page width, see screenshot at bottom of this issue.

Not sure if this can be fixed or not but was going to flag it, this problem occurs in base, wet, GoC web usability and Canada.ca 4.0.11 templates and also on the bootstrap web site (perhaps for all bootstrap implementations). This also occurs in older versions of the templates.

I also apologize if this request is redundant and was flagged ages ago... it was something one of our clients just noticed.

![print-margins](https://cloud.githubusercontent.com/assets/5295103/6420463/4008a434-be94-11e4-87f9-202f5cd31cb8.gif)

**Comment by LaurentGoderre** [comment]
It seems to be occurring on Bootstrap as well 

/cc @cvrebert

**Comment by cvrebert** [comment]
I don't understand what the bug is that you're alleging here. If you scale page content to be smaller, it will of course necessarily take up less space, leaving more blank space on the paper page.

**Comment by cvrebert** [comment]
Also, can you folks get @nschonni to [finally publish a new version of CSSLint?](https://github.com/CSSLint/csslint/issues/514) It's like he has notifications disabled or something.

**Comment by LaurentGoderre** [comment]
@cvrebert yes sorry this is a Firefox behavior not a Bootstrap issue. When I was checking it out I thought the percentage was text size

**Comment by LaurentGoderre** [comment]
@ehcee this is the browser's behavior and there's nothing we can change on our end
