### ISSUE TITLE
Using Bootstrap AddOn to Enter $ Amounts - Accessibility

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#950]
We are seeing GC WET4 forms on Canada.ca pages that use the bootstrap input group addon to convey that the required input is a dollar amount, and that the cents are not required. An example is shown in the image below. 

It was suggested that this implementation would not meet accessibility requirements for the addons. @LaurentGoderre & @thomasgohard had suggestions on how this could be improved. 

Given that there are many interactive GC forms/pages that require input of financial data, I would recommend that this component be added to the Form Validation inputs demo page fairly soon, with the corrective code to improve accessibility. 

![addon dollar amount input](https://cloud.githubusercontent.com/assets/1855584/6445451/f46aa104-c0d1-11e4-8de1-fba85f332eb4.png)

@pcwsmith - this is an action from Friday's meeting

**Comment by thomasgohard** [comment]
What about:
```html
<div class="form-group">
	<label for="netamount">Net amount</label>
	<p id="netamount-desc" class="wb-inv">to the nearest dollar</p>
	<div class="input-group">
		<span class="input-group-addon">$</span>
		<input id="netamount" type="text" class="form-control" aria-describedby="netamount-desc">
		<span class="input-group-addon">.00</span>
	</div>
</div>
```
I tested with Voice Over and it works fine.

@LaurentGoderre or @zachfalsetto can you test with JAWS and NVDA?

**Comment by hsrudnicki** [comment]
@neoinsight @LaurentGoderre or @zachfalsetto : did you received sufficiently positive test results in order to close the issue?
Based on your discussion, only @thomasgohard tested and got good result with Voice Over, however other tests are needed?

**Comment by hsrudnicki** [comment]
Additional note that may help in you decision, here is a example of a bootstrap input field : http://getbootstrap.com/components/#input-groups-basic, and see other example on http://stackoverflow.com/questions/21016472/adding-dollar-prefix-to-bootstrap-input-box

**Comment by neoinsight** [comment]
@hsrudnicki In order to close the issue, the component would need to be added to the Form Validation demo page, with the corrective  code @thomasgohard has suggested. Re testing, I only have access to Voice Over, so we'd need a JAWS and NVDA test as @thomasgohard originally requested. 

P.S. thanks for reminding us about this!

**Comment by neoinsight** [comment]
@thomasgohard @zachfalsetto This field is going to be needed as people onboard and definitely needed in MWS. @thomasgohard proposed a solution in March - would like to close this issue.

**Comment by LaurentGoderre** [comment]
It probably would be simpler to change it to this:

```html
<div class="form-group">
    <label for="netamount">Net amount<span id="netamount-desc" class="wb-inv">, to the nearest dollar</span></label>
    <div class="input-group">
        <span class="input-group-addon">$</span>
        <input id="netamount" type="text" class="form-control" aria-describedby="netamount-desc">
        <span class="input-group-addon">.00</span>
    </div>
</div>
```

Which would read: `Net amount, to the nearest dollar, required` instead of `Net amount. Required. To the nearest dollar.`

**Comment by hsrudnicki** [comment]
Can be this issue closed as resolved/fixed or if otherwise?  If otherwise, label additionally this issue as "Going Stale"? Either way, please update this issue's status, thank you

**Comment by robwloch** [comment]
Our department uses these input-group-addon things where appropriate.

We found the following issue recently and have narrowed it down to the input-group-addon or input-group classes.

We basically have a text field in a table row and the field shrinks on mobile if it's part of an input-group:

``
<td><span class="input-group input-sm"><span class="input-group-addon">$</span><input type="text" size="17" class="form-control" value="Mike@gmail.com"></span></td>
``

![capture-not-shrunk](https://cloud.githubusercontent.com/assets/5721679/12932684/dea5a596-cf51-11e5-978d-e677a252acae.PNG)

``
<td><input type="text" size="17" class="form-control" value="Mike@gmail.com"></td>
``

![capture-shrunk](https://cloud.githubusercontent.com/assets/5721679/12932811/cbeb6728-cf52-11e5-935b-bf9e4ef63566.PNG)

Any help would be appreciated. Thank you.

**Comment by LaurentGoderre** [comment]
@robwloch please open a new issue for this

**Comment by robwloch** [comment]
Hi @LaurentGoderre , okay, I opened https://github.com/wet-boew/wet-boew/issues/7386
under wet-boew

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise? Please update the status of this issue, thank you

**Comment by neoinsight** [comment]
@hsrudnicki, @LaurentGoderre is on leave and no one else has taken this on.

**Comment by hsrudnicki** [comment]
Based on the above, this issue can be closed due to the duplicate issue raised.
