### ISSUE TITLE
Character limit for Canada.ca feedback form

### ISSUE THREAD

**Issue by nrustand92** [wet-boew/GCWeb#952]
@shawnthompson 
Will it be feasible to do a live update of the 250-character limit remaining left for the Canada.ca feedback form in time for R 1.5?  Someone managed to work something out:
https://github.com/wet-boew/wet-boew/issues/6534

Thanks in advance for your input!

**Comment by shawnthompson** [comment]
@MRicher, @lucas-hay and @masterbee: What are your thoughts about using a separate JS plugin file on Canada.ca?

**Comment by MRicher** [comment]
@shawnthompson, @lucas-hay and @masterbee: I see no issues, accept that this should be in WET base and that there should be aria tagging around the message.

**Comment by nrustand92** [comment]
So I'm guessing this is doable then? :)

**Comment by shawnthompson** [comment]
I don't think it'll be that easy. There will have to be some accessibility tests on it before we can implement it.

**Comment by nrustand92** [comment]
@shawnthompson ok.  Would you or someone else be able to do the accessibility test before R 1.5, realistically speaking?  If there are other more pressing priorities, I understand.  I'm only asking b/c I have to show a mockup to management either this week or next, so I just need to know rough timeline, I don't mean to pressure you.

**Comment by shawnthompson** [comment]
@nrustand92 , I don't think this will make the cut for release 1.5 due to all the other priorities and we would really rather have this placed upstream into WET plugins and only use those plugins on Canada.ca.

**Comment by nrustand92** [comment]
Ok thx!

**Comment by hsrudnicki** [comment]
Please update this issue's status whether this issue, referenced with the 968 issue, can be closed as resolved/fixed or otherwise? If otherwise, label additionally this issue as "Going Stale"?  Either way, please keep the status of the issue(s) updated, thank you

**Comment by nrustand92** [comment]
No. This isn't high priority now, but it will have to be revisited

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update again the status of this for the current year, whether this can be closed or otherwise? Thx

**Comment by lucas-hay** [comment]
Closing as feedback form has changed.
