### ISSUE TITLE
Beefing up the demo templates index page

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#954]
Hey there @shawnthompson!  I really like your idea about reorganizing the demo templates index page as a WET table.  Just figured I'd get this in here as an issue, to keep it on the radar.

I was thinking it would benefit from having a column telling people which section of the spec doc to refer to for the full description of each template.  Adding a column for "date updated" would be useful too.  

I've got a Word doc here, with a table building the idea out a little bit.  IE9 won't let me attach it to this issue though... when you get a chance, could you attach the document to this post for me?  I'll send it to you in an email.

You'll see that I've also added a "type" column, and split everything into two tables, to separate out the generic templates from the more strictly prescribed navigation and destination pages.  Just to help people better understand how the various pages/templates should be used.

Interested to hear what you think of it all.  Might be fun to tinker with this when you get some free time  :)

**Comment by shawnthompson** [comment]
I took a quick look at it today. I think we can work with it. I will try mock something up tomorrow or early next week.

**Comment by neoinsight** [comment]
This is a great idea! Am alarmed at the way some of the templates are being used and misused. It would be great to have something similar for GC for navigation components too. 

For example: 

When to use the Advanced Service Initiation template: 
-This template is to be used for a single super task that has steps of subtasks that flow sequentially towards achieving the super task.  
-For example, any service that has eligibility and apply and after you apply steps would be a super task and should use the Advanced Service Initiation template. The advantage is that it keeps the steps of the task together, the user can see the flow, and come back to the super task to see the next step. 

When to use Tabs
-Tabs should be used to see different data/views of a single pre-selected option. 
- Great examples of tab usage are Marine Weather and Travel Advisories. In both cases, a location has been selected from many locations, and the tabs represent different data about that same location. Or statistics  – where the user has chosen a particular industry, and the tabs show all of the different data available about that industry.
-Tabs are not a navigation method – they should not be used to move to different sections of a site.

and so on...

**Comment by hsrudnicki** [comment]
@shawnthompson @DK-TBS @neoinsight : Have been this issue as well as your idea implemented, and can we close it?

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/wet-boew/issues/5574 - WET documentation pages that need to be completed

**Comment by hsrudnicki** [comment]
Is this above still an issue?  Either way, please again update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise? Thank you

**Comment by shawnthompson** [comment]
We can close this issue, we are working on a solution as I write this comment
