### ISSUE TITLE
Fake CIC website

### ISSUE THREAD

**Issue by npjontek** [wet-boew/GCWeb#960]
Fake CIC website discovered today. 
http://www.cicgc-ca.com/

Looks like they are attempting to collect info.
http://www.cicgc-ca.com/enquery.php

Anything we can do to make this harder?

**Comment by LaurentGoderre** [comment]
@npjontek anyone can copy the source of any website and attempt to impersonate it. However doing so usually violates copyrights. I will forward this to the federal identity program.

**Comment by RobJohnston** [comment]
My favourite is Cocaine Anonymous:  http://www.cic.gc.ca.org/

**Comment by jdmlouis** [comment]
Also http://www.cic-gc-ca.com, which is currently domain parked, but registered with the same registrar as the first domain identified.

**Comment by jdmlouis** [comment]
Another thought: this may need to be forwarded to the RCMP, as it appears to be a phishing attempt and therefore impersonation of government official or agency with intent to commit fraud.

**Comment by MRicher** [comment]
There so many of these, this site says and if my Russian is okay, they are the Russian office under CIC.   [http://www.cicru.com/](http://www.cicru.com/)

**Comment by LaurentGoderre** [comment]
The issue was resolved
