### ISSUE TITLE
Possible to change display order on mobile? 

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#969]
Hey @dk-TBS,   @pcwsmith and I were reminded during last month's usability testing that we wished to change the order that the Most Requested box appears in the mobile view. Right now, it shows up AFTER the Topics but it should show up before and sometimes participants bailed off the page before they saw it. Are you the right person to address this issue towards?

In fact, if there are now analytics working, it would be terrific to pick some frequently used topic pages, measure use of the box on mobile and desktop (and bounce rates), THEN change the order and measure again for the same time period. 

Then in the next stage, change the order to display Most Requested at the very top of the page, in a mobile-first design, to measure use and a hypothesis that this would reduce bounce rates. 

In fact, more generally I'm seeing a need to move other page elements into different orders for mobile. In particular the advanced service initiation template strikes me as a concern in mobile (we have only tested a prototype with a few desktop participants). We looked at using it for a particular service, but the service is often used while mobile (mariners), and having all those steps at the top of every page in mobile view meant way too much scrolling before they got to the task content.   

We have some ideas about collapsing the steps into a dropdown or something - will mock it up. Or maybe that should have been a separate issue.

**Comment by thomasgohard** [comment]
That change is simple enough: Change the order of the two blocks in the markup and add the appropriate push/pull grid classes.

I'll try to make the pull request for this in the next few days.

**Comment by pcwsmith** [comment]
I've brought this to the attention of Nic P and co for the analytics angle.

**Comment by DK-TBS** [comment]
Nice!  Collapsing those ordered service initiation steps into a more compact UI element would be great too, if we can find a good way to do it.  That's probably worthy of a separate github issue...

**Comment by neoinsight** [comment]
@DK-TBS Agree - Created new issue for advanced service initiation template - this one is now restricted to the Most Requested box.

**Comment by neoinsight** [comment]
@thomasgohard You mentioned creating a pull request for this in the thread above. Possible to have that  change in place on a dev server by June for testing purposes? We definitely plan some findability tasks in this round with all the new topic pages, would be great to have the box moved on mobile by then to assess the impact. Or could you advise @pcwsmith and I (separately if required) on how this could be implemented and tested?

**Comment by thomasgohard** [comment]
@neoinsight can you confirm on which page templates you want this implemented? The theme page template? The topic page template? Or both?

**Comment by neoinsight** [comment]
@thomasgohard Both was the intention as the issue for mobile occurred on both.

**Comment by thomasgohard** [comment]
OK. Just note though that, on the topics page template, that will also move the "more information for" block ahead of the topics list: http://wet-boew.github.io/themes-dist/GCWeb/topic-en.html.

**Comment by neoinsight** [comment]
@thomasgohard Good point! That's an optional element though, and may even be the best approach via mobile for those audiences. And the block is still AFTER the top tasks, so hopefully many people wouldn't see it. So am still ok with it, but do want @pcwsmith to be aware.

**Comment by thomasgohard** [comment]
@neoinsight @pcwsmith the changes are in #977 and ready to merge if everyone's OK with them.

**Comment by pcwsmith** [comment]
yup, ok that the audience block also comes before the topic link in small screen views. under the current design specs, that optional block won't be used that often.

**Comment by thomasgohard** [comment]
OK. I've merged #977. Someone will have to implement the modified template on Canada.ca or a test page for the usability testing though.

**Comment by neoinsight** [comment]
@thomasgohard Thank you!
