### ISSUE TITLE
GA JavaScript and namespacing conflict

### ISSUE THREAD

**Issue by sylus** [wet-boew/GCWeb#973]
Comparing these two environments:

http://open.canada.ca (Drupal)

http://open.canada.ca/data/en/dataset (CKAN) OR http://canada.ca

You can see on the CKAN or any canada.ca page the last tag element before `</body>` the following JavaScript is inserted:

```
$(document).ajaxStart()?($(document).ready(function(){setupRegularContent();otherEvents()}
...
function checkAltText(a,b){if(""===a||null===a||"undefined"===a||0==a.trim().length)a='alt\x3d"'+$(b).find("img").attr("alt")+'"';return a};
```

Unfortunately this JavaScript is not properly namespaced and frameworks that provide jQuery in no conflict mode won't work. This above JavaScript should be following the jQuery plugins authoring guidelines and wrap the $ element.

<code>
(function($) {
    // Here $ is the jQuery namespace.
})(jQuery);
</code>

In addition looking over this JavaScript I had a few other issues related to performance and why this JavaScript include isn't in the GCWeb repository?

**Comment by sylus** [comment]
@pjackson28 @LaurentGoderre

**Comment by LaurentGoderre** [comment]
Unfortunately that is not the centralization of the features. We are investigating.

**Comment by masterbee** [comment]
@sylus, @LaurentGoderre  - Thanks for this, we have found the generator of this JS and it is coming from the GA implementation in the GCWeb theme. We are digging deeper into how to encapsulate and optimize this and will follow up soon.

Thanks for catching this. :+1:

**Comment by sylus** [comment]
Thanks a bunch for looking into this!

**Comment by masterbee** [comment]
@sylus - We have started to work on the optimization of this script but have just pushed a modified version that encapsulated. Let me know if this helps. 

/cc @lucas-hay

**Comment by sylus** [comment]
Works great for me and no longer have a javascript error.

Thanks for the quick turnaround!
