### ISSUE TITLE
Facebook widget functionality after Facebook activity feed stops working on June/23/2015

### ISSUE THREAD

**Issue by ehcee** [wet-boew/GCWeb#979]
On the facebook web site:
https://developers.facebook.com/docs/plugins/activity

It's saying with the release of graph 2.3, the activity feed will stop working on June 23, 2015.

Does this impact the functionality of the facebook widget as i believe we currently just point them to feeds. Was wondering if the facebook widget was going to stop working after June 23rd, another another solution/implementation being developed, or the faceboo widget is not affected by this?

We have a few campaigns coming up the facebook widget in them and wondering if they'll still work?

**Comment by LaurentGoderre** [comment]
@thomasgohard does this affect us?

**Comment by LaurentGoderre** [comment]
Can you post to the core WET repo?

**Comment by thomasgohard** [comment]
This should not affect us. From what I can tell the Activity Feeds is a widget you embed in your page. We're using an ATOM feed, for the Facebook feeds.

**Comment by MaximMartel** [comment]
Looking into this issue right now. 
http://wet-boew.github.io/themes-dist/GCWeb/widgets-en.html, the last feed for Facebook is 22th of june 2015, like mentioned in first post.

**Comment by MaximMartel** [comment]
https://developers.facebook.com/docs/plugins/page-plugin i believe its there alternative.

**Comment by thomasgohard** [comment]
Looks like Facebook has indeed deprecated the Feeds API and replaced it with `/v2.3/{page_id}/feed` in the Graph API. This new API returns JSON, not ATOM.

So the Feeds plugin would need to be rewritten to use the new API for Facebook.

**Comment by MaximMartel** [comment]
Understood, thanks @thomasgohard .

**Comment by andre-gh** [comment]
Looking into it we would need an oath API key and secret (in the wet JS or in the DOM of the page) for that to work correctly.  Is there any precedent for API keys in WET?

If not I strongly suggest clients using the Facebook RSS feeds replace it with the pages embed plugin Facebook provides for public use like that.

**Comment by LaurentGoderre** [comment]
We usually don't use services that requires secret keys.

**Comment by andre-gh** [comment]
Clients embedding Facebook page widgets would be limited to one page/feed per widget though if they were to migrate....at a quick glance the first public page I could find using it was a single feed (but that was just a quick glance).  The other downsides I can see are off themeing and a lack of control over the widget itself as far as accessibility/content goes.

**Comment by andre-gh** [comment]
For reference it looks something like this: 

![feeed](https://cloud.githubusercontent.com/assets/13316676/8938562/4d91e7e0-352d-11e5-8327-f89ee397d572.png)

**Comment by MaximMartel** [comment]
Should i go ahead and start to work to implement the page plugin of Facebook : https://developers.facebook.com/docs/plugins/page-plugin instead of our widget since it no longer work after they updated to graph 2.3? 

@LaurentGoderre  @thomasgohard

**Comment by hsrudnicki** [comment]
Is this above still an issue?  Either way, please update this issue's status whether this issue can be closed as resolved or if otherwise?  Thank you

Due to no further discussion/status update(s), additionally label this issue as "Going Stale"?

**Comment by hsrudnicki** [comment]
Please update the status of this issue whether this can be closed or otherwise?  Thank you

**Comment by lucas-hay** [comment]
Addressed by #7010
