### ISSUE TITLE
Promo overlay covers search field on mobile 

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#984]
Usability participant is attempting to search. Has hit button, search opens. Promo comes up over top of his search field, cannot see the field. Tries to push it down out of the way, it rises back up. Has to hit x to close it. See video for sequence - notice it rising up over the field. Notice also how much of the usable screen is has seized. Android phone - Chrome.  http://youtu.be/LooBNB4btjQ

![promo overlays search mobile p6](https://cloud.githubusercontent.com/assets/1855584/7971006/c53ae498-0a0f-11e5-84a0-fecf92ccc76f.png)

Overlays should not interfere with user's most recent action, particularly search where they may already be typing.

**Comment by neoinsight** [comment]
Should have copied to: @masterbee and @pcwsmith

**Comment by masterbee** [comment]
@neoinsight - Thanks for this. We are investigating as well. @pcwsmith and @neoinsight  what are  your thoughts that the banner not be available in mobile view? I am not sure the real estate will ever be there with view ports as small as some devices.

**Comment by neoinsight** [comment]
@masterbee that's a good idea to me. The banner is quite disruptive on that small space. It's even possible that some day there could be an alternative that is better suited for mobile, involving longer time delays such that it appears later in a session, and one that doesn't overlay interactive elements like menus, buttons or fields.

**Comment by pcwsmith** [comment]
I would definitely support not having the promo banner on small screens.

**Comment by masterbee** [comment]
@neoinsight , @pcwsmith - Just wanted to let you know that the promo now disappears in mobile with the latest tweaks that were added. 

Closing issue since resolved. Many thanks everyone for there feedback and vigilance

**Comment by pcwsmith** [comment]
thanks @masterbee - looks like the dismiss button has been adjusted also... is it now based on the session or is there a specific time period where it is dismissed?
