### ISSUE TITLE
"xxyy" showing on bottom left of all pages

### ISSUE THREAD

**Issue by RobJohnston** [wet-boew/GCWeb#988]
Likely related to https://github.com/wet-boew/wet-boew/issues/6246

See the current pages here:
 * http://wet-boew.github.io/themes-dist/GCWeb/splashpage.html
 * http://wet-boew.github.io/themes-dist/GCWeb/servermessage-en.html

They are showing the same "xxyy" on the left-hand side.

**Comment by RobJohnston** [comment]
Correction, its' also showing on the content pages:
  * http://wet-boew.github.io/themes-dist/GCWeb/content-en.html

**Comment by LaurentGoderre** [comment]
Yeah, this is sort of a duplicate #986

**Comment by pjackson28** [comment]
Note that PR wet-boew/wet-boew#6874 will hide this check with CSS in case jQuery doesn't load for whatever reason.
