### ISSUE TITLE
Data tables - how to implement other options from Data Tables API 

### ISSUE THREAD

**Issue by sophiek4905** [wet-boew/GCWeb#990]
#1 
complex headers
http://www.datatables.net/examples/advanced_init/complex_header.html

column rendering
http://www.datatables.net/examples/advanced_init/column_render.html

#2
<table class="wb-tables table table-striped table-hover" data-wb-tables='{ "ordering" : false }'>
is it possible to disable ordering for certain columns  only ?

**Comment by RobJohnston** [comment]
Yes, I've done it before.  The documentation is here:  http://datatables.net/reference/option/columns.orderable

For example, to disable ordering for the first column, you'd do something like this:
```html
<table class="wb-tables table table-striped table-hover" data-wb-tables='{ "columns": [
    { "orderable": false },
    null,
    null,
    null,
    null
  ]}' id="wb-auto-2">
```

**Comment by sophiek4905** [comment]
Thanks Rob.  What is the syntax if using it in Javascript rather than through the data-wb-tables attribute?  

 

I want to hide some columns when the table is first loaded.  Then user can click a button to toggle to display/hide the columns. 

 

$(document).ready(function() {

    $('#example').dataTable( {

        "columnDefs": [

            {

                "targets": [ 2 ],

                "visible": false,

                "searchable": false

            },

            {

                "targets": [ 3 ],

                "visible": false

            }

        ]

    } );

} );

**Comment by RobJohnston** [comment]
Guessing here, but from the [documentation] (http://datatables.net/reference/option/columns.orderable#), wouldn't you just put *"orderable": :false* in your column definition?  Somebody more front-end can expand on this if not correct.

```javascript
wb.doc.on("wb-ready.wb", function (event) {
  $('#example').dataTable( {
        "columnDefs": [
            {
                "targets": [ 2 ],
                "visible": false,
                "searchable": false,
                "orderable": false
            },
            {
                "targets": [ 3 ],
                "visible": false
            }
        ]
    } );
});
```

**Comment by pjackson28** [comment]
For the hiding on the initial load you would just do it through data-wb-tables. As for how to change it after load, I found the following: http://datatables.net/examples/api/show_hide.html. Their example needs some cleanup (e.g., switching to the wb-ready.wb) but you should be able to use the "visible" column method to show/hide the column after the load.

**Comment by sophiek4905** [comment]
after initial load, displays this  warning: 

![image](https://cloud.githubusercontent.com/assets/3309149/8338209/bc58482e-1a7d-11e5-8ea0-d348e13e7a46.png)

However after clicked ok, show/hide works perfectly.  

<script type="text/javascript" class="init">
$(document).on("wb-ready.wb", function() {
	var table = $('#example').DataTable( {
		"scrollY": "200px",
		"paging": false
	} );

	$('a.toggle-vis').on( 'click', function (e) {
		e.preventDefault();

		// Get the column API object
		var column = table.column( $(this).attr('data-column') );

		// Toggle the visibility
		column.visible( ! column.visible() );
	} );
} );
	</script>

**Comment by pjackson28** [comment]
Yes, that is why you should only be initializing through data-wb-tables. Your JS that calls dataTable( {} ) is attempting to reinitialize the table after WET has already initialized it (using what is in data-wb-tables as the parameters). The alert will go away if you just initialize with data-wb-tables and then have add the click listener to change the visibility after the fact.

**Comment by sophiek4905** [comment]
Thank you.  It works.

**Comment by pjackson28** [comment]
Can this issue be closed?

**Comment by sophiek4905** [comment]
Yes, Thanks again
