### ISSUE TITLE
Incorrect translation on FR simple service initiation template needs a quick-fix

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#992]
One of the departments has picked up a bad translation that we're using on the "apply" button on the french simple service initiation template.  "Postulez maintenant" should be "Faites une demande", or simply "Demandez" if we need something shorter.

Quote:  "Please NO NOT USE Postulez as TBS suggested, because “postuler” means to apply for a job. If applying for a benefit, “faites une demande” or “demandez” is to be used. “Appliquez” is also wrong, if anyone suggests it!"

**Comment by LaurentGoderre** [comment]
Demandez looks weird to me. Faire une demande is way better IMO

**Comment by DK-TBS** [comment]
Let's run with that, then - no need to constrain ourselves to just one word.  Happy to have your eyes on it, Mr Laurent   :)

**Comment by nschonni** [comment]
http://www.btb.termiumplus.gc.ca/tpv2alpha/alpha-eng.html?lang=eng&i=&index=alt&__index=alt&srchtxt=apply&comencsrch.x=0&comencsrch.y=0&comencsrch=Launch

**Comment by hsrudnicki** [comment]
Is this still an issue?  Either way, please update this issue's status whether this issue can be closed as resolved/fixed or if otherwise?
Additionally, label this issue as "Going Stale"?

**Comment by DK-TBS** [comment]
It looks like the corrected translation hasn't yet been applied to the FR simple service initiation template, so we should keep this issue open for now.

**Comment by hsrudnicki** [comment]
Please update again this issue's status for the current year, whether this can be closed or otherwise, thank you

**Comment by RobJohnston** [comment]
I've also seen "Présenter une demande" already in use on the [IRCC website] (http://www.cic.gc.ca/francais/information/demandes/visa.asp), which is record #12 in Nick's link above.  Don't know if this is better than "Faire une demande".

**Comment by DK-TBS** [comment]
Probably best to leave this issue open, as the [demo template in question](http://wet-boew.github.io/themes-dist/GCWeb/service-fr.html) has yet to be updated to use "Faire une demande" on that button.  Maybe @shawnthompson can make that little fix next time he's working on those templates?

**Comment by shawnthompson** [comment]
How did I miss this... I'll do it tomorrow when I'm in.
